//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectSummary
    {
        public int id { get; set; }
        public Nullable<int> Projectid { get; set; }
        public string ProjectNo { get; set; }
        public string FinancialYear { get; set; }
        public string ProjectType { get; set; }
        public Nullable<System.DateTime> ProjectApprovalDate { get; set; }
        public string PIname { get; set; }
        public Nullable<decimal> SanctionedValue { get; set; }
        public string SanctionOrderNo { get; set; }
        public Nullable<System.DateTime> SanctionOrderDate { get; set; }
        public string ProjectDuration { get; set; }
        public Nullable<decimal> OverheadsReceived { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> TotalReceipt { get; set; }
        public Nullable<decimal> AmountSpent { get; set; }
        public Nullable<decimal> PreviousCommitment { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> AvailableBalance { get; set; }
        public Nullable<decimal> ApprovedNegativeBalance { get; set; }
        public Nullable<decimal> NetBalance { get; set; }
        public Nullable<decimal> BaseValue { get; set; }
        public Nullable<decimal> ApplicableTax { get; set; }
        public string ProjectCategory { get; set; }
        public string ProjectClassification { get; set; }
    }
}
