//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectExpenditureSummary
    {
        public int id { get; set; }
        public Nullable<int> Projectid { get; set; }
        public Nullable<int> Allocationheadid { get; set; }
        public string AllocationheadName { get; set; }
        public Nullable<int> YearSeq { get; set; }
        public Nullable<decimal> AllocationAmount { get; set; }
        public Nullable<decimal> ExpenditureAmount { get; set; }
        public Nullable<decimal> OpenCommitment { get; set; }
    }
}
