//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOASExternal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayinSlip
    {
        public int PayinslipId { get; set; }
        public string PayinslipReferenceNumber { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> PIId { get; set; }
        public Nullable<int> Sequencenumber { get; set; }
        public Nullable<decimal> AmountReceived { get; set; }
        public Nullable<decimal> ITTdsReceived { get; set; }
        public Nullable<decimal> GSTTdsReceived { get; set; }
        public string ModeofPayment { get; set; }
        public string ReferenceNumber { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> OutstandingAmount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> UpdtTS { get; set; }
        public Nullable<int> UpdtUserId { get; set; }
        public Nullable<System.DateTime> InstrumentsDate { get; set; }
        public Nullable<bool> IsSend_f { get; set; }
    }
}
