//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOASExternal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwUserAD
    {
        public long Pkey { get; set; }
        public string ID { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string Email { get; set; }
        public string loginid { get; set; }
        public string CONNumber { get; set; }
        public int Adhocf { get; set; }
        public Nullable<int> UserId { get; set; }
        public string InvoicePIId { get; set; }
    }
}
