//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSREMP.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ICSRExternalEntities : DbContext
    {
        public ICSRExternalEntities()
            : base("name=ICSRExternalEntities")
        {
            this.Database.CommandTimeout = 180;
            this.Database.ExecuteSqlCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;");        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdminEmployeeaccess> tblAdminEmployeeaccess { get; set; }
        public virtual DbSet<tblCodeControl> tblCodeControl { get; set; }
        public virtual DbSet<tblDepartment> tblDepartment { get; set; }
        public virtual DbSet<tblEmailLog> tblEmailLog { get; set; }
        public virtual DbSet<tblFinYear> tblFinYear { get; set; }
        public virtual DbSet<tblFunction> tblFunction { get; set; }
        public virtual DbSet<tblMenuGroup> tblMenuGroup { get; set; }
        public virtual DbSet<tblModules> tblModules { get; set; }
        public virtual DbSet<tblNotification> tblNotification { get; set; }
        public virtual DbSet<tblPaySlipMonth> tblPaySlipMonth { get; set; }
        public virtual DbSet<tblProjectStaffLoginDetails> tblProjectStaffLoginDetails { get; set; }
        public virtual DbSet<tblProjectStaffUser> tblProjectStaffUser { get; set; }
        public virtual DbSet<tblRole> tblRole { get; set; }
        public virtual DbSet<tblRoleaccess> tblRoleaccess { get; set; }
        public virtual DbSet<TempOnging> TempOnging { get; set; }
    
        public virtual int SPUserCreation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPUserCreation");
        }
    }
}
