//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSREMP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectStaffUser
    {
        public int ProjectStaffId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> Crts_Ts { get; set; }
        public Nullable<int> PaybillNo { get; set; }
        public string Designation { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public Nullable<System.DateTime> Uptd_Ts { get; set; }
        public Nullable<int> Uptd_Id { get; set; }
    }
}
