//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class adhocMissedComDetail
    {
        public int ID { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> PaymentHeadId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<double> CommitmentBalance { get; set; }
        public Nullable<double> GrossTotal { get; set; }
        public Nullable<double> CommitmentBooked { get; set; }
        public string OtherAllowance { get; set; }
        public Nullable<double> NetSalary { get; set; }
        public Nullable<double> diff { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> PaymentMonthYear { get; set; }
        public string Type { get; set; }
        public Nullable<int> sNo { get; set; }
        public Nullable<int> CommitmentDetId { get; set; }
    }
}
