//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class backendRecRMF
    {
        public string CategoryId { get; set; }
        public string Bank { get; set; }
        public Nullable<double> BankAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> ReceiptAmount { get; set; }
        public string ModeOfReceipt { get; set; }
        public string Project { get; set; }
        public Nullable<int> bankid { get; set; }
        public Nullable<int> projectid { get; set; }
        public string status { get; set; }
        public int id { get; set; }
        public Nullable<int> ReceiptID { get; set; }
        public Nullable<int> CommitmentID { get; set; }
    }
}
