//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestEarned20_21
    {
        public string CategoryId { get; set; }
        public string Bank { get; set; }
        public string BankAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> ReceiptAmount { get; set; }
        public Nullable<double> ModeOfReceipt { get; set; }
        public string Project { get; set; }
        public string bankid { get; set; }
        public string projectid { get; set; }
        public string status { get; set; }
        public int id { get; set; }
        public string ReceiptID { get; set; }
        public string CommitmentID { get; set; }
    }
}
