//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4333394337344538
    {
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public string Type { get; set; }
        public string Projectnumber { get; set; }
        public string Receiptnumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AgencyName { get; set; }
        public Nullable<decimal> Amountreceived { get; set; }
        public Nullable<decimal> Taxvalue { get; set; }
        public Nullable<decimal> OH { get; set; }
        public Nullable<int> FinYearId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Description { get; set; }
        public string Coordname { get; set; }
    }
}
