//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4631374344413446
    {
        public int DesignationDetailId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> Qualification { get; set; }
        public Nullable<int> Marks { get; set; }
        public Nullable<int> RelevantExperience { get; set; }
        public Nullable<int> CrtdUser { get; set; }
        public Nullable<System.DateTime> CrtdTs { get; set; }
        public Nullable<int> UptdUser { get; set; }
        public Nullable<System.DateTime> UptdTs { get; set; }
        public Nullable<bool> IsCurrentVersion { get; set; }
        public Nullable<int> CGPA { get; set; }
        public bool IsSelectAll { get; set; }
    }
}
