//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4441464636443142
    {
        public int OHReversalShareId { get; set; }
        public Nullable<int> OHReversalId { get; set; }
        public Nullable<int> PIid { get; set; }
        public Nullable<int> PCFProjectId { get; set; }
        public Nullable<int> RMFProjectId { get; set; }
        public string Role { get; set; }
        public Nullable<decimal> PCFper { get; set; }
        public Nullable<decimal> PCFvalue { get; set; }
        public Nullable<decimal> RMFper { get; set; }
        public Nullable<decimal> RMFvalue { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> CRTD_BY { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public Nullable<int> UPTD_BY { get; set; }
    }
}
