//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4532433641374645
    {
        public int ProcessCodeId { get; set; }
        public Nullable<int> FunctionId { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> MinimumValue { get; set; }
        public Nullable<decimal> MaximumValue { get; set; }
        public Nullable<int> FlowId { get; set; }
        public string ActionLink { get; set; }
        public string FailureService { get; set; }
        public string ClarifyService { get; set; }
        public string SuccessService { get; set; }
        public string TransactionTypeCode { get; set; }
        public string Status { get; set; }
    }
}
