//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4446303133363930
    {
        public int InvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> PIId { get; set; }
        public string TaxCode { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public string DescriptionofServices { get; set; }
        public Nullable<decimal> TaxableValue { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> TotalInvoiceValue { get; set; }
        public string TotalInvoiceValueinWords { get; set; }
        public Nullable<int> Bank { get; set; }
        public string BankAccountNumber { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> UpdtTS { get; set; }
        public Nullable<int> UpdtUserId { get; set; }
        public Nullable<int> InstalmentYear { get; set; }
        public Nullable<int> InstalmentNumber { get; set; }
        public string PONumber { get; set; }
        public string CommunicationAddress { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<int> FinancialYear { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public string AgencyRegName { get; set; }
        public Nullable<int> AgencyRegState { get; set; }
        public Nullable<int> AgencyRegStateCode { get; set; }
        public string AgencyRegGSTIN { get; set; }
        public string AgencyRegPAN { get; set; }
        public Nullable<int> ExternalRefId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> InvoiceValueinForeignCurrency { get; set; }
        public string AgencyDistrict { get; set; }
        public string AgencyRegTAN { get; set; }
        public Nullable<int> AgencyPincode { get; set; }
        public string AgencyContactPersonName { get; set; }
        public string AgencyContactPersonEmail { get; set; }
        public string AgencyContactPersonNumber { get; set; }
        public Nullable<int> AgencyCountry { get; set; }
        public Nullable<int> CreditLedgerId { get; set; }
        public Nullable<int> CreditLedgerGroupId { get; set; }
        public Nullable<int> IndianSEZTaxCategory { get; set; }
        public string ForeignAgencyPlace { get; set; }
        public Nullable<bool> ReverseCharge { get; set; }
        public string IRNno { get; set; }
        public string ApplicationNo { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public string IRNDocumentName { get; set; }
        public string IRNDocumentActualName { get; set; }
    }
}
