//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3543383942413444
    {
        public int CorpusLogId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransactionType { get; set; }
        public string TypeCode { get; set; }
        public Nullable<int> RefId { get; set; }
        public string RefNo { get; set; }
        public Nullable<bool> Pmt_f { get; set; }
        public string Status { get; set; }
    }
}
