//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4531344336384632
    {
        public int OverallAnnualAccountsId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectType { get; set; }
        public string SanctionOrderNumber { get; set; }
        public string ProjectTitle { get; set; }
        public string PIName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public Nullable<decimal> sanctionValue { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> Receipts { get; set; }
        public Nullable<decimal> Staff { get; set; }
        public Nullable<decimal> Consumables { get; set; }
        public Nullable<decimal> Contingencies { get; set; }
        public Nullable<decimal> Travel { get; set; }
        public Nullable<decimal> Component { get; set; }
        public Nullable<decimal> Overheads { get; set; }
        public Nullable<decimal> Equipment { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<decimal> Miscellaneous { get; set; }
        public Nullable<decimal> TotalExpenditure { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<decimal> NegativeApprove { get; set; }
        public Nullable<decimal> Commitments { get; set; }
        public Nullable<decimal> SponReceipt { get; set; }
        public Nullable<decimal> SponExp { get; set; }
    }
}
