//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4443434239383441
    {
        public int LoginId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string IPaddress { get; set; }
        public Nullable<bool> Login_f { get; set; }
    }
}
