//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3944423337324444
    {
        public int SalaryUploadId { get; set; }
        public Nullable<int> TypeOfPayBill { get; set; }
        public string PaymentMonthYear { get; set; }
        public string GuId { get; set; }
        public string DocName { get; set; }
        public string ActualName { get; set; }
        public Nullable<System.DateTime> Crtd_TS { get; set; }
        public Nullable<int> Crtd_By { get; set; }
    }
}
