//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3546333646353343
    {
        public int RCTPayrollId { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> SalaryType { get; set; }
        public string SalaryMonth { get; set; }
        public Nullable<System.DateTime> SalaryMonthDate { get; set; }
        public string Status { get; set; }
        public string AppointmentType { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<decimal> AgencyFee { get; set; }
        public Nullable<decimal> GST { get; set; }
    }
}
