//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4533373438394139
    {
        public int EmailId { get; set; }
        public string ToMail { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Cc { get; set; }
        public string Bcc { get; set; }
        public string Attachment { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_Ts { get; set; }
        public Nullable<System.DateTime> UPTD_Ts { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public Nullable<int> TypeofMail { get; set; }
        public Nullable<int> AnnouncementID { get; set; }
    }
}
