//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3741373737443936
    {
        public int StatutoryId { get; set; }
        public Nullable<decimal> PFEmployeePercentage { get; set; }
        public Nullable<decimal> PFEmployerPercentage { get; set; }
        public Nullable<decimal> ESICEmployeePercentage { get; set; }
        public Nullable<decimal> ESICEmployerPercentage { get; set; }
        public Nullable<decimal> LWFEmployeeContribution { get; set; }
        public Nullable<decimal> LWFEmployerContribution { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<int> CrtdUser { get; set; }
        public Nullable<System.DateTime> CrtdTs { get; set; }
        public Nullable<int> UptdUser { get; set; }
        public Nullable<System.DateTime> UptdTs { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsCurrentVersion { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> PFEmployeeAmount { get; set; }
        public Nullable<decimal> ESICEmployeePhysicalAmount { get; set; }
        public Nullable<decimal> ESICEmployeegeneralamount { get; set; }
    }
}
