//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3444453538324539
    {
        public int MaxOrderId { get; set; }
        public int HistoryID { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> DesignationId { get; set; }
    }
}
