//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4433444239423434
    {
        public int HeadCreditInvoiceDetailsId { get; set; }
        public Nullable<int> HeadCreditId { get; set; }
        public string ReversedInvoiceNumber { get; set; }
        public Nullable<decimal> ReversedInvoiceAmount { get; set; }
        public Nullable<decimal> ReversedInvoiceGSTAmount { get; set; }
    }
}
