//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4533413038423436
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string PrevStatus { get; set; }
        public string ModifiedStatus { get; set; }
        public Nullable<int> Crtd_By { get; set; }
        public Nullable<System.DateTime> Crtd_Ts { get; set; }
    }
}
