//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3938453239443931
    {
        public int RCTCommitteeApprovalLogId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string ApplicationCategory { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public string Action { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> OrderId { get; set; }
    }
}
