//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4336433244333243
    {
        public int OHReversalId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Corpus { get; set; }
        public Nullable<decimal> PCF { get; set; }
        public Nullable<decimal> RMF { get; set; }
        public Nullable<decimal> ICSROH { get; set; }
        public Nullable<decimal> DDF { get; set; }
        public Nullable<decimal> StaffWelfare { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> CRTD_BY { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public Nullable<int> UPTD_BY { get; set; }
        public Nullable<int> CheckListVerifiedBy { get; set; }
        public string OHReversalNumber { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ProjectType { get; set; }
    }
}
