//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3634313336323432
    {
        public int OSGNotesID { get; set; }
        public Nullable<int> OSGId { get; set; }
        public string PICommends { get; set; }
        public string HRNote { get; set; }
        public Nullable<System.DateTime> Crt_TS { get; set; }
    }
}
