//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3444304632353338
    {
        public int OTHLogId { get; set; }
        public Nullable<int> OTHPayDeductionId { get; set; }
        public string PresentStatus { get; set; }
        public string NewStatus { get; set; }
        public Nullable<int> preby { get; set; }
        public Nullable<int> Crt_By { get; set; }
        public Nullable<System.DateTime> Crt_Ts { get; set; }
        public Nullable<int> Upt_By { get; set; }
        public string Message { get; set; }
    }
}
