//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3931334333443634
    {
        public int Id { get; set; }
        public string RefNumber { get; set; }
        public Nullable<int> RefId { get; set; }
        public string FunctionName { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> AmountModified { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> CRTD_BY { get; set; }
        public Nullable<int> NegativeBalanceId { get; set; }
        public string NegativeBalanceNumber { get; set; }
    }
}
