//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3746423744423543
    {
        public int SalaryUploadDetailId { get; set; }
        public Nullable<int> PayBill { get; set; }
        public string FileNumber { get; set; }
        public string Name { get; set; }
        public string Dept { get; set; }
        public string Designation { get; set; }
        public string DesignationCode { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string BankName { get; set; }
        public string BankAccountNo { get; set; }
        public string IFSC_Code { get; set; }
        public string Branch { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PAN { get; set; }
        public Nullable<decimal> PreviouseSalary { get; set; }
        public Nullable<decimal> PreviousPT { get; set; }
        public Nullable<decimal> PreviousIT { get; set; }
        public Nullable<decimal> ProjectedSalary { get; set; }
        public string ProjectNo { get; set; }
        public string CommitmentNo { get; set; }
        public Nullable<decimal> CommitmentBalance { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> MISS_PAY { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> MISS_HRA_PAY { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> IncomeTax { get; set; }
        public Nullable<decimal> MISS_REC { get; set; }
        public Nullable<decimal> MedicalInsurance { get; set; }
        public Nullable<decimal> LLP { get; set; }
        public Nullable<decimal> PROF_TAX { get; set; }
        public Nullable<decimal> TotalDeducation { get; set; }
        public Nullable<decimal> NetPay { get; set; }
        public Nullable<decimal> OtherPay { get; set; }
        public string ValidationMessage { get; set; }
        public Nullable<int> SalaryUploadId { get; set; }
        public Nullable<int> MA_AllocationHeadId { get; set; }
    }
}
