//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3830394430323534
    {
        public int AnnouncementPlatform { get; set; }
        public Nullable<int> AnnouncementID { get; set; }
        public bool Naukri { get; set; }
        public bool indeed { get; set; }
        public bool linkedin { get; set; }
        public bool Recruitmentportal { get; set; }
        public bool Others { get; set; }
    }
}
