//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4346324136383034
    {
        public int FinYearwiseProjSummaryBreakUpId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<int> FinYear { get; set; }
        public Nullable<decimal> Staff { get; set; }
        public Nullable<decimal> Consumables { get; set; }
        public Nullable<decimal> Contingencies { get; set; }
        public Nullable<decimal> Travel { get; set; }
        public Nullable<decimal> Component { get; set; }
        public Nullable<decimal> Overheads { get; set; }
        public Nullable<decimal> Equipment { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<decimal> PublicationMonograph { get; set; }
        public Nullable<decimal> WorkshopSymposium { get; set; }
        public Nullable<decimal> ScientificSocialResponsibility { get; set; }
        public Nullable<decimal> IPFee { get; set; }
        public Nullable<decimal> Miscellaneous { get; set; }
        public Nullable<decimal> FieldTestingDemoTraining { get; set; }
        public Nullable<decimal> Software { get; set; }
        public Nullable<decimal> ConsumablesTravelContingencies { get; set; }
        public Nullable<decimal> ConsumablesTravel { get; set; }
        public Nullable<decimal> Refundofunspentbalance { get; set; }
        public Nullable<decimal> Refundofunspentinterest { get; set; }
        public Nullable<decimal> FieldWork { get; set; }
        public Nullable<decimal> EquipmentandStudyMaterial { get; set; }
        public Nullable<decimal> PublicationofReport { get; set; }
        public Nullable<decimal> OverheadsContingencies { get; set; }
        public Nullable<decimal> Consultants { get; set; }
        public Nullable<decimal> ConsumablesandAccessories { get; set; }
        public Nullable<decimal> ConsultancyFees { get; set; }
        public Nullable<decimal> OtherInstituteShare { get; set; }
        public Nullable<decimal> UnspentBalance { get; set; }
        public Nullable<decimal> InterestRefund { get; set; }
        public Nullable<decimal> Distribution { get; set; }
        public Nullable<decimal> Outsourcing { get; set; }
        public Nullable<decimal> Expenditure { get; set; }
        public Nullable<decimal> Receipt { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
    }
}
