//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4346353339443932
    {
        public int ConsultantAppointmentLogId { get; set; }
        public Nullable<int> ConsultantAppointmentId { get; set; }
        public Nullable<int> TypeofAppointment { get; set; }
        public Nullable<int> ProfessionalType { get; set; }
        public string CandidateImage { get; set; }
        public string Name { get; set; }
        public string NameoftheGuardian { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string PermanentAddress { get; set; }
        public string TemporaryAddress { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<System.DateTime> ApplicationReceiveDate { get; set; }
        public Nullable<System.DateTime> ApplicationEntryDate { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankName { get; set; }
        public string IFSCCode { get; set; }
        public string PanNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<System.DateTime> AppointmentStartdate { get; set; }
        public Nullable<System.DateTime> AppointmentEnddate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> GSTApplicable { get; set; }
        public Nullable<decimal> GSTPercentage { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string CommitmentNumber { get; set; }
        public Nullable<decimal> CommitmentAmount { get; set; }
        public Nullable<int> FormType { get; set; }
        public string PIJustificationRemarks { get; set; }
        public Nullable<bool> IsICSRStafforProjectStaff { get; set; }
        public string Comments { get; set; }
        public string Note { get; set; }
        public string ApplicationNumber { get; set; }
        public string Status { get; set; }
        public Nullable<int> CommitteeMember { get; set; }
        public Nullable<int> CommitteeMembers { get; set; }
        public Nullable<int> Chairperson { get; set; }
        public Nullable<bool> NotetoPI { get; set; }
        public Nullable<bool> NotetoCommittee { get; set; }
        public Nullable<bool> NotetoDean { get; set; }
        public Nullable<bool> Nodeviation { get; set; }
        public Nullable<int> CrtdUser { get; set; }
        public Nullable<System.DateTime> CrtdTs { get; set; }
        public Nullable<int> UptdUser { get; set; }
        public Nullable<System.DateTime> UptdTs { get; set; }
        public Nullable<int> SqNbr { get; set; }
        public Nullable<int> IITMPensionerorCSIRStaff { get; set; }
        public string ReasonForCancel { get; set; }
        public string Bcc { get; set; }
        public Nullable<bool> GovernmentProofVerify { get; set; }
        public Nullable<int> GovernmentProofVerifyDoc { get; set; }
        public string EmergencyContact { get; set; }
        public string CandidateSignature { get; set; }
        public Nullable<System.DateTime> OfferDate { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public string JoiningReport { get; set; }
        public string VerificationRemarks { get; set; }
        public Nullable<bool> isEmployee { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string EmployeersID { get; set; }
        public Nullable<int> VerificationSeqNo { get; set; }
        public string AlternativeContactNumber { get; set; }
        public string CommitteeRemarks { get; set; }
        public Nullable<int> CommitteeApprovedBy { get; set; }
        public string ToMail { get; set; }
        public Nullable<bool> IsSameAsPresentAddress { get; set; }
        public string AadhaarNumber { get; set; }
        public string PPONo { get; set; }
        public Nullable<int> CSIRStaffPayMode { get; set; }
        public Nullable<bool> isCommitmentReject { get; set; }
        public string NIDNumber { get; set; }
        public string OldNumber { get; set; }
        public string EmployeeCategory { get; set; }
        public bool Fellowship { get; set; }
        public bool NotetoCMAdmin { get; set; }
        public Nullable<int> BankId { get; set; }
        public bool ConsolidatedPay { get; set; }
        public Nullable<System.DateTime> ActualAppointmentEndDate { get; set; }
        public Nullable<System.DateTime> ActualAppointmentStartDate { get; set; }
        public string EmployeeWorkplace { get; set; }
        public string ResumeFile { get; set; }
        public bool IsActiveNow { get; set; }
        public string OfficeOrder { get; set; }
        public string OfferLetter { get; set; }
        public string FormFile { get; set; }
        public Nullable<System.DateTime> RelieveDate { get; set; }
        public string CommitmentNo { get; set; }
        public Nullable<System.DateTime> OfficeOrderDate { get; set; }
        public Nullable<int> RequestedBy { get; set; }
        public string RefNumber { get; set; }
        public string FileNo { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<System.DateTime> LOGCRTD_TS { get; set; }
        public Nullable<int> LOGCRTD_USER { get; set; }
    }
}
