//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4445464135344638
    {
        public int STEEducatioLogID { get; set; }
        public Nullable<int> STELogID { get; set; }
        public Nullable<int> STEEducationDetailID { get; set; }
        public Nullable<int> STEID { get; set; }
        public Nullable<int> QualifiCationID { get; set; }
        public Nullable<int> DisciplineID { get; set; }
        public string UniversityorInstitution { get; set; }
        public Nullable<int> YearOfPassing { get; set; }
        public Nullable<decimal> Marks { get; set; }
        public string DivisionClassObtained { get; set; }
        public string DocumentFilePath { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CrtdUser { get; set; }
        public Nullable<System.DateTime> CrtdTs { get; set; }
        public Nullable<int> UptdUser { get; set; }
        public Nullable<System.DateTime> UptdTs { get; set; }
        public Nullable<bool> isCurrentVersion { get; set; }
        public string FileName { get; set; }
        public Nullable<int> MarkType { get; set; }
    }
}
