//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3634453143414143
    {
        public int ProcessTransactionFunctionRefId { get; set; }
        public string RefTable { get; set; }
        public string RefField { get; set; }
        public string FunctionName { get; set; }
        public Nullable<int> FunctionId { get; set; }
        public string TransactionTypeCode { get; set; }
        public string ViewName { get; set; }
    }
}
