//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3944363445413141
    {
        public int RCTPayrollProcessDetailId { get; set; }
        public Nullable<int> RCTPayrollDetailId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string AppointmentType { get; set; }
        public Nullable<decimal> CurrentBasic { get; set; }
        public Nullable<decimal> CurrentHRA { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<decimal> CurrentMedical { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<bool> MedicalInclusive_f { get; set; }
        public Nullable<System.DateTime> AppointmentEndDate { get; set; }
        public Nullable<System.DateTime> RelieveDate { get; set; }
        public Nullable<System.DateTime> AppointmentStartDate { get; set; }
        public string CandidateName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public string CommitmentNumber { get; set; }
        public string ProjectNumber { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationCode { get; set; }
        public Nullable<bool> TaxExempted { get; set; }
        public Nullable<bool> PTExempted { get; set; }
        public Nullable<decimal> Spl_Allowance { get; set; }
        public Nullable<decimal> Transport_Allowance { get; set; }
        public Nullable<decimal> PF_Revision { get; set; }
        public Nullable<decimal> ESIC_Revision { get; set; }
        public Nullable<decimal> Round_off { get; set; }
        public Nullable<decimal> Arrears { get; set; }
        public Nullable<decimal> OthersPay { get; set; }
        public Nullable<decimal> Contribution_to_PF { get; set; }
        public Nullable<decimal> Recovery { get; set; }
        public Nullable<decimal> OthersDeduction { get; set; }
        public Nullable<decimal> Professional_tax { get; set; }
        public Nullable<decimal> Loss_Of_Pay { get; set; }
        public Nullable<decimal> Medical_Recovery { get; set; }
        public string Salutation { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string Branch { get; set; }
        public string IFSC { get; set; }
        public Nullable<int> TotalDaysInMonth { get; set; }
        public string ProcessStatus { get; set; }
        public string SalaryMonth { get; set; }
        public Nullable<int> SalaryType { get; set; }
        public string SalaryProcessType { get; set; }
        public Nullable<int> RCTPayrollId { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_Ts { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_Ts { get; set; }
        public Nullable<decimal> HRA_Arrears { get; set; }
        public Nullable<decimal> HRA_Recovery { get; set; }
    }
}
