//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4434304636453346
    {
        public int CommitteeMemberDetailID { get; set; }
        public Nullable<int> AnnouncementID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Destination { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Institution { get; set; }
        public Nullable<int> PIUserID { get; set; }
        public string DestinationName { get; set; }
        public string DepartmentName { get; set; }
    }
}
