//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3139463043384442
    {
        public int ReceiptBreakupId { get; set; }
        public Nullable<int> ReceiptId { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_Ts { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_Ts { get; set; }
        public string Status { get; set; }
        public string ReferenceNumber { get; set; }
        public string DocumentName { get; set; }
        public string ActualDocumentName { get; set; }
    }
}
