//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4341383542353538
    {
        public int HeadCreditHeadDetailsId { get; set; }
        public Nullable<int> HeadCreditId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> BudgetHeadId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransactionType { get; set; }
    }
}
