//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3336314339413332
    {
        public int OTHPayDeductionDetailId { get; set; }
        public Nullable<int> OTHPayDeductionId { get; set; }
        public Nullable<int> OtherType { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> DeductionType { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> HeadId { get; set; }
    }
}
