//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3638453330463131
    {
        public int ContId { get; set; }
        public Nullable<decimal> MA { get; set; }
        public string EmployeeId { get; set; }
        public string ProjectNo { get; set; }
        public Nullable<int> PayBill { get; set; }
        public int PaymentId { get; set; }
        public Nullable<int> PaymentHeadId { get; set; }
        public Nullable<decimal> CommitAmt { get; set; }
        public string commitmentNo { get; set; }
        public Nullable<int> commitmentDetId { get; set; }
        public Nullable<int> commitmentId { get; set; }
        public Nullable<int> projectId { get; set; }
        public string salProcessedProjectNo { get; set; }
    }
}
