//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3634323344374331
    {
        public int BRSReconcileMappingId { get; set; }
        public Nullable<int> BRSDetailId { get; set; }
        public Nullable<int> BOAPaymentDetailId { get; set; }
    }
}
