//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4133443142453342
    {
        public int ImprestBankStatemenDetailId { get; set; }
        public Nullable<int> ImprestBankStatementId { get; set; }
        public string ImprestAccountNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionNo { get; set; }
        public string Type { get; set; }
        public string Particulars { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> BillBookingAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public string Status { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
    }
}
