//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4545444438393238
    {
        public string Employee_No { get; set; }
        public string Name { get; set; }
        public string Project_No { get; set; }
        public Nullable<double> INST { get; set; }
        public Nullable<int> projectId { get; set; }
        public Nullable<int> headId { get; set; }
        public Nullable<int> commitmentId { get; set; }
        public Nullable<int> commtmentDetailId { get; set; }
        public int paymentid { get; set; }
    }
}
