//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4643314335303344
    {
        public int Id { get; set; }
        public string WFreferencenbr { get; set; }
        public string WFreferencetype { get; set; }
        public Nullable<int> Referenceid { get; set; }
        public string Referencenbr { get; set; }
        public Nullable<int> CRTD_BY { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<bool> IsDelete_f { get; set; }
    }
}
