//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3235314530383845
    {
        public int SubHeadId { get; set; }
        public Nullable<int> AllocationId { get; set; }
        public string Subhead { get; set; }
        public Nullable<decimal> AllocationValue { get; set; }
        public string Status { get; set; }
    }
}
