//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3338424239464338
    {
        public string sender { get; set; }
        public string host { get; set; }
        public int emailport { get; set; }
        public string emailpassword { get; set; }
        public bool EnableMail { get; set; }
    }
}
