//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4544453831464138
    {
        public int BOACommitmentDetailId { get; set; }
        public Nullable<int> RefId { get; set; }
        public string ReferenceNumber { get; set; }
        public string TransactionTypeCode { get; set; }
        public string CommitmentNumber { get; set; }
        public Nullable<int> CommitmentDetailId { get; set; }
        public Nullable<int> HeadId { get; set; }
        public string HeadName { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
