//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3937353742353438
    {
        public int AnnouncementID { get; set; }
        public string RefNo { get; set; }
        public string AnnouncementTitle { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> AnnouncementCategory { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RequestedBy { get; set; }
        public string DAComments { get; set; }
        public Nullable<int> ModeOfRequest { get; set; }
        public Nullable<System.DateTime> RequestReceiveDate { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public Nullable<System.DateTime> InterviewScheduleDate { get; set; }
        public Nullable<System.DateTime> DraftedDate { get; set; }
        public string Crt_By { get; set; }
        public Nullable<System.DateTime> Crt_TS { get; set; }
        public Nullable<int> Crt_User { get; set; }
        public Nullable<int> Upt_User { get; set; }
        public string CanceledReason { get; set; }
        public string Remark { get; set; }
        public string RemarkDoc { get; set; }
        public string NoteDocument { get; set; }
        public string ShortlistNoteDocument { get; set; }
        public string SelectionlistNoteDocument { get; set; }
        public Nullable<System.DateTime> Upt_TS { get; set; }
        public string FlowApprover { get; set; }
        public string FlowApprover2 { get; set; }
        public string FlowApprover3 { get; set; }
        public Nullable<int> PIName { get; set; }
        public Nullable<int> YearlySeq { get; set; }
        public string Remark2 { get; set; }
    }
}
