//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tapaltempview
    {
        public Nullable<System.DateTime> DateTimeReceipt { get; set; }
        public Nullable<System.DateTime> InwardDateTime { get; set; }
        public Nullable<int> TapalType { get; set; }
        public string SenderDetail { get; set; }
        public string TapalNo { get; set; }
        public string Notes { get; set; }
        public string Forwardedby { get; set; }
        public string ProjectCategory { get; set; }
        public string PrjNumber { get; set; }
        public string Comments { get; set; }
        public string Receiver { get; set; }
        public Nullable<System.DateTime> OutwardDateTime { get; set; }
    }
}
