//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnnualAccounts
    {
        public int AnnualAccounts { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectType { get; set; }
        public string SanctionOrderNumber { get; set; }
        public string ProjectTitle { get; set; }
        public string PIName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public Nullable<decimal> sanctionValue { get; set; }
        public Nullable<decimal> SponReceipt { get; set; }
        public Nullable<decimal> SponExp { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> Allo_Staff { get; set; }
        public Nullable<decimal> Allo_Consumables { get; set; }
        public Nullable<decimal> Allo_Contingencies { get; set; }
        public Nullable<decimal> Allo_Travel { get; set; }
        public Nullable<decimal> Allo_Component { get; set; }
        public Nullable<decimal> Allo_Overheads { get; set; }
        public Nullable<decimal> Allo_Equipment { get; set; }
        public Nullable<decimal> Allo_Others { get; set; }
        public Nullable<decimal> Allo_PublicationMonograph { get; set; }
        public Nullable<decimal> Allo_WorkshopSymposium { get; set; }
        public Nullable<decimal> Allo_ScientificSocialResponsibility { get; set; }
        public Nullable<decimal> Allo_IPFee { get; set; }
        public Nullable<decimal> Allo_Miscellaneous { get; set; }
        public Nullable<decimal> Allo_FieldTestingDemoTraining { get; set; }
        public Nullable<decimal> Allo_Software { get; set; }
        public Nullable<decimal> Allo_ConsumablesTravelContingencies { get; set; }
        public Nullable<decimal> Allo_ConsumablesTravel { get; set; }
        public Nullable<decimal> Allo_Refundofunspentbalance { get; set; }
        public Nullable<decimal> Allo_Refundofunspentinterest { get; set; }
        public Nullable<decimal> Allo_FieldWork { get; set; }
        public Nullable<decimal> Allo_EquipmentandStudyMaterial { get; set; }
        public Nullable<decimal> Allo_PublicationofReport { get; set; }
        public Nullable<decimal> Allo_OverheadsContingencies { get; set; }
        public Nullable<decimal> Allo_Consultants { get; set; }
        public Nullable<decimal> Allo_ConsumablesandAccessories { get; set; }
        public Nullable<decimal> Allo_ConsultancyFees { get; set; }
        public Nullable<decimal> Allo_ConsumablesTravelContingenciesOtherCost { get; set; }
        public Nullable<decimal> Allo_UnspentBalance { get; set; }
        public Nullable<decimal> Allo_InterestRefund { get; set; }
        public Nullable<decimal> Allo_Distribution { get; set; }
        public Nullable<decimal> Allo_Outsourcing { get; set; }
        public Nullable<decimal> Receipts { get; set; }
        public Nullable<decimal> Staff { get; set; }
        public Nullable<decimal> Consumables { get; set; }
        public Nullable<decimal> Contingencies { get; set; }
        public Nullable<decimal> Travel { get; set; }
        public Nullable<decimal> Component { get; set; }
        public Nullable<decimal> Overheads { get; set; }
        public Nullable<decimal> Equipment { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<decimal> PublicationMonograph { get; set; }
        public Nullable<decimal> WorkshopSymposium { get; set; }
        public Nullable<decimal> ScientificSocialResponsibility { get; set; }
        public Nullable<decimal> IPFee { get; set; }
        public Nullable<decimal> Miscellaneous { get; set; }
        public Nullable<decimal> FieldTestingDemoTraining { get; set; }
        public Nullable<decimal> Software { get; set; }
        public Nullable<decimal> ConsumablesTravelContingencies { get; set; }
        public Nullable<decimal> ConsumablesTravel { get; set; }
        public Nullable<decimal> Refundofunspentbalance { get; set; }
        public Nullable<decimal> Refundofunspentinterest { get; set; }
        public Nullable<decimal> FieldWork { get; set; }
        public Nullable<decimal> EquipmentandStudyMaterial { get; set; }
        public Nullable<decimal> PublicationofReport { get; set; }
        public Nullable<decimal> OverheadsContingencies { get; set; }
        public Nullable<decimal> Consultants { get; set; }
        public Nullable<decimal> ConsumablesandAccessories { get; set; }
        public Nullable<decimal> ConsultancyFees { get; set; }
        public Nullable<decimal> ConsumablesTravelContingenciesOtherCost { get; set; }
        public Nullable<decimal> UnspentBalance { get; set; }
        public Nullable<decimal> InterestRefund { get; set; }
        public Nullable<decimal> Distribution { get; set; }
        public Nullable<decimal> Outsourcing { get; set; }
        public Nullable<decimal> TotalExpenditure { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<decimal> NegativeApprove { get; set; }
        public Nullable<decimal> Commitment { get; set; }
        public string ProjectSchemeCode { get; set; }
        public string AgencyName { get; set; }
        public string ProposalNumber { get; set; }
        public string ProjectClassification { get; set; }
    }
}
