//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChequePrintSize
    {
        public int ChequeSizeId { get; set; }
        public string ChequeCharacter { get; set; }
        public Nullable<int> ChequeSizeX { get; set; }
        public Nullable<int> ChequeSizeY { get; set; }
    }
}
