//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDelegationDetail
    {
        public int DelegationDetailId { get; set; }
        public Nullable<int> DelegationId { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<int> PrevDelegation { get; set; }
        public Nullable<int> CurrDelegation { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> HeaderId { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> CRTD_ID { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public Nullable<int> UPTD_ID { get; set; }
        public string Status { get; set; }
    }
}
