//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDynamicSummary
    {
        public Nullable<int> ReportID { get; set; }
        public string ReportField { get; set; }
        public string Aggregation { get; set; }
        public Nullable<bool> GroupBy { get; set; }
        public Nullable<bool> OrderBy { get; set; }
        public int DynamicSummaryId { get; set; }
    }
}
