//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForm3c
    {
        public int Form3cId { get; set; }
        public Nullable<int> Form3cTypeId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectTitle { get; set; }
        public string AgencyName { get; set; }
        public string PAN { get; set; }
        public string Address { get; set; }
        public string PurposeProgramme { get; set; }
        public string RefNoandDate { get; set; }
        public string DateOfApp { get; set; }
        public string StartDate { get; set; }
        public string ProgDuration { get; set; }
        public string AssYear { get; set; }
        public string ProgCost { get; set; }
        public string Installment { get; set; }
        public string RecNo { get; set; }
        public string RecAmt { get; set; }
        public string CheqNo { get; set; }
        public string Cheqdate { get; set; }
        public string TotalRecAmt { get; set; }
        public string NoOfPayments { get; set; }
        public string DeanName { get; set; }
        public string NatureOfBuss { get; set; }
        public string AnnualTurnOver { get; set; }
        public Nullable<int> CRTD_BY { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public string Status { get; set; }
        public Nullable<int> RecId { get; set; }
        public string VoucherNumber { get; set; }
        public string FinalDocuments { get; set; }
        public string NewlyGeneratedDoc { get; set; }
        public string AnnualResearch { get; set; }
        public string DeductionDetails { get; set; }
        public string AgreementDetails { get; set; }
    }
}
