//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFinYearwiseProjSummary
    {
        public int FinYearwiseProjSummaryId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<int> FinYear { get; set; }
        public Nullable<decimal> Receipt { get; set; }
        public Nullable<decimal> Expenditure { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
    }
}
