//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectSummaryChart
    {
        public int ProjectSummaryChartId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProjectCount { get; set; }
        public Nullable<decimal> ProjectCost { get; set; }
        public Nullable<decimal> Receipt { get; set; }
        public Nullable<decimal> Expenditure { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Type { get; set; }
    }
}
