//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectNotConsiderForMailRpt
    {
        public int ProjectNotConsiderId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> Allocation_f { get; set; }
        public Nullable<bool> SanctionValue_f { get; set; }
        public Nullable<bool> NegativeProject_f { get; set; }
        public string ProjectNumber { get; set; }
    }
}
