//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTOSGEducationDetailLog
    {
        public int OSGEducationLogID { get; set; }
        public Nullable<int> OSGLogID { get; set; }
        public Nullable<int> OSGEducationDetailId { get; set; }
        public Nullable<int> OSGId { get; set; }
        public Nullable<int> QualificationId { get; set; }
        public Nullable<int> DisciplineId { get; set; }
        public string UniversityorInstitution { get; set; }
        public Nullable<int> YearOfPassing { get; set; }
        public Nullable<decimal> Marks { get; set; }
        public string DivisionClassObtained { get; set; }
        public string DocumentFile { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CrtdUser { get; set; }
        public Nullable<System.DateTime> CrtdTs { get; set; }
        public Nullable<int> UptdUser { get; set; }
        public Nullable<System.DateTime> UptdTs { get; set; }
        public string Status { get; set; }
        public Nullable<bool> isCurrentVersion { get; set; }
        public string FileName { get; set; }
        public string DocumentFilePath { get; set; }
        public Nullable<int> MarkType { get; set; }
    }
}
