//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTSTE_31Mar2021_
    {
        public string FileNo { get; set; }
        public string TypeofAppointment { get; set; }
        public string EmployeeCategory { get; set; }
        public Nullable<int> NIDNumber { get; set; }
        public string OldNumber { get; set; }
        public string CandidateImage { get; set; }
        public string ProfessionalType { get; set; }
        public string Name { get; set; }
        public string NameoftheGuardian { get; set; }
        public Nullable<int> AadhaarNumber { get; set; }
        public string PANNo { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Caste { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> AlternativeContactNumber { get; set; }
        public string Email { get; set; }
        public Nullable<bool> isSameAsPresentAddress { get; set; }
        public string Present_Address { get; set; }
        public string Permanent_Address { get; set; }
        public Nullable<int> Bloodgroup { get; set; }
        public Nullable<int> BloodgroupRH { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string PhysicallyChallenged { get; set; }
        public string RelatedIIT { get; set; }
        public Nullable<int> Relationship { get; set; }
        public Nullable<int> RelationshipDetails { get; set; }
        public Nullable<System.DateTime> ApplicationEntryDate { get; set; }
        public Nullable<System.DateTime> ApplicationReceiveDate { get; set; }
        public Nullable<bool> ConsolidatedPay { get; set; }
        public Nullable<bool> Fellowship { get; set; }
        public string IITMPensionerOrCSIRStaff { get; set; }
        public Nullable<double> PPONo { get; set; }
        public string CSIRStaffPayMode { get; set; }
        public Nullable<bool> MsPhd { get; set; }
        public Nullable<int> PhdDetail { get; set; }
        public string ProjectId { get; set; }
        public string ProjectNo { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string Medical { get; set; }
        public Nullable<System.DateTime> AppointmentStartdate { get; set; }
        public Nullable<System.DateTime> AppointmentEnddate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> MedicalAmount { get; set; }
        public Nullable<bool> isHaveHRA { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public string CommitmentNo { get; set; }
        public string SalaryPayHigh { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankName { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<int> CommitteeMember { get; set; }
        public Nullable<int> CommitteeMembers { get; set; }
        public Nullable<int> Chairperson { get; set; }
        public Nullable<int> NotetoPI { get; set; }
        public Nullable<int> NotetoCommittee { get; set; }
        public Nullable<int> NotetoDean { get; set; }
        public Nullable<int> Nodeviation { get; set; }
        public Nullable<int> CrtdUser { get; set; }
        public System.DateTime CrtdTs { get; set; }
        public Nullable<int> UptdUser { get; set; }
        public Nullable<int> UptdTs { get; set; }
        public Nullable<int> isHaveGateScore { get; set; }
        public Nullable<int> GateScore { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public string StaffCategory { get; set; }
        public Nullable<int> CanceledReason { get; set; }
        public Nullable<int> GovernmentProofVerify { get; set; }
        public Nullable<int> GovernmentProofVerifyDoc { get; set; }
        public Nullable<int> EmergencyContact { get; set; }
        public Nullable<int> EmployeeType { get; set; }
        public Nullable<int> CandidateSignature { get; set; }
        public Nullable<System.DateTime> OfferDate { get; set; }
        public Nullable<int> JoiningReport { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public Nullable<int> VerificationRemarks { get; set; }
        public Nullable<int> isEmployee { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> VerificationSeqNo { get; set; }
        public Nullable<int> ToMail { get; set; }
        public Nullable<int> bcc { get; set; }
        public Nullable<int> CommiteeRemarks { get; set; }
        public Nullable<int> CommiteeApprovedBy { get; set; }
        public Nullable<int> Remarks { get; set; }
        public Nullable<int> Comments { get; set; }
        public Nullable<int> HRNote { get; set; }
        public Nullable<decimal> HRAPercentage { get; set; }
        public Nullable<int> isCommitmentReject { get; set; }
        public Nullable<int> NoteToCMAdmin { get; set; }
        public Nullable<int> isGovtAgencyFund { get; set; }
        public string OfferLetter { get; set; }
        public Nullable<int> OfficeOrder { get; set; }
        public Nullable<int> RelieveDate { get; set; }
        public string RollNumber { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> isLossofpay { get; set; }
        public Nullable<bool> isStoppayment { get; set; }
        public Nullable<int> ActualAppointmentStartDate { get; set; }
        public Nullable<int> ActualAppointmentEndDate { get; set; }
        public Nullable<bool> isActiveNow { get; set; }
        public Nullable<int> EmployeeWorkplace { get; set; }
        public Nullable<int> ResumeFile { get; set; }
        public Nullable<int> MsPhdType { get; set; }
        public Nullable<System.DateTime> OfficeOrderDate { get; set; }
    }
}
