//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTSalaryLevelDetail
    {
        public int SalaryLevelDetailId { get; set; }
        public Nullable<int> SalaryLevelId { get; set; }
        public Nullable<int> Qualification { get; set; }
        public Nullable<int> Marks { get; set; }
        public Nullable<int> CGPA { get; set; }
        public Nullable<int> RelevantExperience { get; set; }
        public Nullable<int> CRTD_BY { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> UPDT_BY { get; set; }
        public Nullable<System.DateTime> UPDT_TS { get; set; }
        public Nullable<bool> IsCurrentVersion { get; set; }
    }
}
