//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTSTEOngoingExperienceDetail_31Mar2021_
    {
        public string STEID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Organisation { get; set; }
        public string Designation { get; set; }
        public string FromYear { get; set; }
        public string ToYear { get; set; }
        public string SalaryDrawn { get; set; }
        public Nullable<int> DocumentFilePath { get; set; }
        public Nullable<int> Remarks { get; set; }
        public Nullable<int> CrtdUser { get; set; }
        public Nullable<int> CrtsTs { get; set; }
        public Nullable<int> UptdUser { get; set; }
        public Nullable<int> UptdTs { get; set; }
        public Nullable<bool> isCurrentVersion { get; set; }
    }
}
