//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTConsultantMasterLog
    {
        public int Consultant_MasterId { get; set; }
        public string Consultant_EmpId { get; set; }
        public int Consultant_Nationality { get; set; }
        public int Consultant_Category { get; set; }
        public string Consultant_EmpType { get; set; }
        public Nullable<int> Consultant_Salutation { get; set; }
        public string Consultant_Name { get; set; }
        public Nullable<int> Consultant_Gender { get; set; }
        public Nullable<System.DateTime> Consultant_DOB { get; set; }
        public string Consultant_ContactNumber { get; set; }
        public string Consultant_Email { get; set; }
        public string Consultant_AadhaarNo { get; set; }
        public string Consultant_PanNo { get; set; }
        public string Consultant_Address { get; set; }
        public string Consultant_Details { get; set; }
        public string Consultant_Qualification { get; set; }
        public string Consultant_Experience { get; set; }
        public string Consultant_Photo { get; set; }
        public Nullable<int> Consultant_Country { get; set; }
        public string Consultant_City { get; set; }
        public Nullable<int> Consultant_StateId { get; set; }
        public Nullable<int> Consultant_StateCode { get; set; }
        public string Consultant_Pincode { get; set; }
        public string Consultant_ServiceAddress { get; set; }
        public string Consultant_AccountHolderName { get; set; }
        public string Consultant_BankName { get; set; }
        public string Consultant_Branch { get; set; }
        public string Consultant_IFSC { get; set; }
        public string Consultant_AccountNumber { get; set; }
        public string Consultant_BankAddress { get; set; }
        public string Consultant_ABANumber { get; set; }
        public string Consultant_SortCode { get; set; }
        public string Consultant_IBAN { get; set; }
        public string Consultant_SWIFTorBICCode { get; set; }
        public string Consultant_BankNature { get; set; }
        public string Consultant_MICRCode { get; set; }
        public Nullable<int> Consultant_BankCountry { get; set; }
        public string Consultant_BankEmailId { get; set; }
        public Nullable<int> CrtdUser { get; set; }
        public Nullable<System.DateTime> CrtdTs { get; set; }
        public Nullable<int> UptdUser { get; set; }
        public Nullable<System.DateTime> UptdTs { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActiveNow { get; set; }
        public Nullable<bool> isSameAsAddress { get; set; }
        public Nullable<int> SeqNbr { get; set; }
        public string Consultant_TIN { get; set; }
        public Nullable<bool> IsGST { get; set; }
        public string GSTIN { get; set; }
        public Nullable<bool> CurrentVersion { get; set; }
    }
}
