//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTOfferDetail
    {
        public int OfferDetailId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string Category { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OfferCategory { get; set; }
        public Nullable<bool> isSend { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public Nullable<int> CRTD_USER { get; set; }
        public Nullable<int> UPTD_USER { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<int> OrderwiseSeqNo { get; set; }
        public string OfferRefNumber { get; set; }
    }
}
