//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTSalaryComponentTxLog
    {
        public int SalaryComponentTxLogId { get; set; }
        public Nullable<int> ComponentType { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> wefDate { get; set; }
        public Nullable<System.DateTime> wetDate { get; set; }
        public Nullable<int> OrderId { get; set; }
        public bool IsRelisedStopPayment { get; set; }
        public Nullable<System.DateTime> RelivedDate { get; set; }
        public string EmployeeId { get; set; }
    }
}
