//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTCancelApplicationLog
    {
        public int CancelLogId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> AppointmentType { get; set; }
        public string CancelReason { get; set; }
        public string CancelDocument { get; set; }
        public Nullable<int> CrtUser { get; set; }
        public Nullable<int> UptUser { get; set; }
        public Nullable<System.DateTime> CrtTs { get; set; }
        public Nullable<System.DateTime> UptTs { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string PreStatus { get; set; }
    }
}
