//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTOrderRequest
    {
        public int OrderRequestId { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public Nullable<int> AppointmentType { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> OldSalary { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> OldProjectId { get; set; }
        public Nullable<int> NewProjectId { get; set; }
        public Nullable<int> OldDesignationId { get; set; }
        public Nullable<int> NewDesignationId { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Extend_f { get; set; }
        public Nullable<bool> ProjectChange_f { get; set; }
        public Nullable<bool> SalaryChange_f { get; set; }
        public Nullable<bool> Designation_f { get; set; }
        public Nullable<bool> Relieving_f { get; set; }
        public Nullable<bool> LOP_f { get; set; }
        public Nullable<decimal> WithdrawAmount { get; set; }
        public Nullable<decimal> CommitmentAmount { get; set; }
        public Nullable<int> CRTD_BY { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> UPTD_BY { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public Nullable<int> RelieveMode { get; set; }
        public Nullable<bool> NoDues_f { get; set; }
        public string NoDuesRemark { get; set; }
        public string NoDuesDoc { get; set; }
        public string NoDuesDocName { get; set; }
        public Nullable<System.DateTime> ExistingFromDate { get; set; }
        public Nullable<System.DateTime> ExistingToDate { get; set; }
        public string OtherDesignation { get; set; }
    }
}
