//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTConsultantROP_OTHPay
    {
        public int OtherPaymentsDeductionId { get; set; }
        public Nullable<int> PaymentReleaseId { get; set; }
        public Nullable<int> OtherType { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CommitmentAmount { get; set; }
        public Nullable<System.DateTime> OtherPaymentsDeduction_CrtdTs { get; set; }
        public Nullable<int> OtherPaymentsDeduction_CrtdUser { get; set; }
        public Nullable<int> DeductionType { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> HeadId { get; set; }
    }
}
