//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTCONOldOrderHistory
    {
        public string FileNo { get; set; }
        public Nullable<int> OrderId { get; set; }
        public int OrderTypeReference { get; set; }
        public string OrderType { get; set; }
        public string ApplicationId { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public Nullable<System.DateTime> ActualAppointmentEndDate { get; set; }
        public decimal Basic { get; set; }
        public string DesignationId { get; set; }
        public string PROJECTNO { get; set; }
        public string ProjectId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public Nullable<int> RelieveMode { get; set; }
        public string AppointmentType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> Migrated { get; set; }
        public Nullable<int> GST { get; set; }
        public Nullable<int> GSTApplicable { get; set; }
        public int ID { get; set; }
    }
}
