//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTOTHPaymentDeductionLog
    {
        public int OTHPayDeductionLogId { get; set; }
        public Nullable<int> OTHPayDeductionId { get; set; }
        public Nullable<int> OtherType { get; set; }
        public string EmployeeNo { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public Nullable<int> AppointmentType { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> CrtdUser { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<int> UpdtUser { get; set; }
        public Nullable<System.DateTime> UpdtTs { get; set; }
        public string Status { get; set; }
        public string OTHPayDeductionNo { get; set; }
        public Nullable<int> DeductionType { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> DesignationId { get; set; }
    }
}
