//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTSTE_Awaiting_VerificationEntry
    {
        public Nullable<double> S_NO { get; set; }
        public Nullable<System.DateTime> OFFER_DATE { get; set; }
        public string OLD_FILE__NUMBER { get; set; }
        public string NAME { get; set; }
        public string PROECT_NO { get; set; }
        public string OLD___NEW { get; set; }
        public string DEG { get; set; }
        public Nullable<double> SALARY { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public string REMARKS { get; set; }
        public string DELAY_DUE_TO { get; set; }
        public string COMMITMENT_NUMBR { get; set; }
        public string TEST_1 { get; set; }
        public string TEST_2 { get; set; }
        public bool TRUE { get; set; }
        public string ACTIVE { get; set; }
        public string REMARKES { get; set; }
        public string UpdatedCommitment { get; set; }
    }
}
