//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTConsultantEntryDocs
    {
        public int Consultant_DocumentId { get; set; }
        public int Consultant_MasterId { get; set; }
        public int Consultant_AppointmentId { get; set; }
        public int Consultant_DocumentType { get; set; }
        public string Consultant_DocumentRemarks { get; set; }
        public string Consultant_DocumentName { get; set; }
        public string Consultant_DocumentNameEncrypted { get; set; }
        public System.DateTime Consultant_CrtdTs { get; set; }
        public int Consultant_CrtdUser { get; set; }
        public Nullable<System.DateTime> Consultant_UptdTs { get; set; }
        public Nullable<int> Consultant_UptdUser { get; set; }
        public string Consultant_Status { get; set; }
        public bool Consultant_IsDeleted { get; set; }
    }
}
