//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTAnnouncementDetails
    {
        public int DestinationDeatailID { get; set; }
        public Nullable<int> AnnouncementID { get; set; }
        public Nullable<int> Destination { get; set; }
        public string DestinationCode { get; set; }
        public string DestinationName { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<int> Vacancies { get; set; }
        public string Qualification { get; set; }
        public Nullable<decimal> MinSalary { get; set; }
        public Nullable<decimal> MaxSalary { get; set; }
        public Nullable<int> TotalApplicantsNumber { get; set; }
        public Nullable<int> ShortlistedApplicantsNumber { get; set; }
        public Nullable<int> SelectedApplicantsNumber { get; set; }
        public string TotalApplicantsDoc { get; set; }
        public string ShortlistedApplicantsDoc { get; set; }
        public string SelectedApplicantsDoc { get; set; }
        public bool isCurrentVersion { get; set; }
        public Nullable<int> ProjectID { get; set; }
    }
}
