//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTOSGPayroll
    {
        public int RCTOSGPayrollId { get; set; }
        public int RCTPayrollDetailId { get; set; }
        public int RCTPayrollId { get; set; }
        public string Employee_ID { get; set; }
        public string Salutation { get; set; }
        public string Employee_Name { get; set; }
        public string Designation { get; set; }
        public string Employment_Mode { get; set; }
        public string Deapartment { get; set; }
        public string Project_Number { get; set; }
        public string Commitment_Number { get; set; }
        public string Process_Type { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<decimal> Recommended_Salary { get; set; }
        public Nullable<decimal> Gross_Salary { get; set; }
        public Nullable<decimal> PF_BASIC { get; set; }
        public Nullable<decimal> Total_Working_Days { get; set; }
        public Nullable<decimal> LOP { get; set; }
        public Nullable<decimal> Employee_Working_Days { get; set; }
        public Nullable<decimal> Gross_Salary_For_the_Month { get; set; }
        public Nullable<decimal> Recovery { get; set; }
        public Nullable<decimal> Additional_Pay { get; set; }
        public string Insurance { get; set; }
        public string PF_Eligibility { get; set; }
        public string ESIC_Eligiblity { get; set; }
        public Nullable<decimal> InsuranceAmt { get; set; }
        public Nullable<decimal> InsuranceAmount_CM { get; set; }
        public Nullable<decimal> EmployeePF { get; set; }
        public Nullable<decimal> EmployeeESIC { get; set; }
        public Nullable<decimal> EmployerPF { get; set; }
        public Nullable<decimal> EmployerESIC { get; set; }
        public Nullable<decimal> EmployeePF_CM { get; set; }
        public Nullable<decimal> EmployeeESIC_CM { get; set; }
        public Nullable<decimal> EmployerPF_CM { get; set; }
        public Nullable<decimal> EmployerESIC_CM { get; set; }
        public Nullable<decimal> Calculated_Pay { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string Branch { get; set; }
        public string IFSC { get; set; }
        public Nullable<System.DateTime> RelieveDate { get; set; }
        public Nullable<decimal> ctc { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> DaysInMonth { get; set; }
        public Nullable<System.DateTime> DOE { get; set; }
        public Nullable<decimal> CTC_CM { get; set; }
        public Nullable<decimal> EmployeePT { get; set; }
    }
}
