//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCM
    {
        public int RCMId { get; set; }
        public string RefNumber { get; set; }
        public Nullable<int> Refid { get; set; }
        public string TransactionTypecode { get; set; }
        public string VendorName { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> Invoicedate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TaxPer { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<bool> Interstate_f { get; set; }
        public string GSTIN { get; set; }
        public Nullable<bool> Offset_f { get; set; }
        public Nullable<bool> Credit_f { get; set; }
        public Nullable<System.DateTime> Date_f { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> CRTD_By { get; set; }
    }
}
