//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTConsultantROP
    {
        public int PaymentReleaseId { get; set; }
        public int Consultant_MasterId { get; set; }
        public int Consultant_AppointmentId { get; set; }
        public decimal Consultant_RetainerFee { get; set; }
        public bool FeeType { get; set; }
        public System.DateTime PaymentFromDate { get; set; }
        public System.DateTime PaymentToDate { get; set; }
        public decimal BasicAmount { get; set; }
        public Nullable<decimal> GSTPercentage { get; set; }
        public Nullable<decimal> GSTValue { get; set; }
        public Nullable<decimal> InvoiceValue { get; set; }
        public Nullable<decimal> OtherPayment { get; set; }
        public decimal GrossPay { get; set; }
        public Nullable<decimal> ITTDSPercentage { get; set; }
        public Nullable<decimal> ITTDSValue { get; set; }
        public Nullable<decimal> GSTTDSValue { get; set; }
        public decimal NetAmount { get; set; }
        public System.DateTime PaymentRelease_CrtdTs { get; set; }
        public int PaymentRelease_CrtdUser { get; set; }
        public Nullable<System.DateTime> PaymentRelease_UptdTs { get; set; }
        public Nullable<int> PaymentRelease_UptdUser { get; set; }
        public string PaymentRelease_Status { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<decimal> GSTTDSPercentage { get; set; }
        public Nullable<decimal> CurrencyValue { get; set; }
        public Nullable<decimal> ConversionRate { get; set; }
        public Nullable<decimal> NewConversion_Rate { get; set; }
        public Nullable<decimal> CurrentandArrear_Aount { get; set; }
    }
}
