//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTOrderEffectHistory
    {
        public int HistoryID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public Nullable<System.DateTime> ActualAppointmentEndDate { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public string AppointmentType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<bool> isHRABooking { get; set; }
        public Nullable<System.DateTime> HRABookingDate { get; set; }
        public Nullable<bool> isHRACancellation { get; set; }
        public Nullable<System.DateTime> HRACancellationDate { get; set; }
        public Nullable<bool> isMedicalInclusive { get; set; }
        public Nullable<System.DateTime> AppointmentStartDate { get; set; }
        public Nullable<System.DateTime> AppointmentEndDate { get; set; }
        public Nullable<System.DateTime> Relievedate { get; set; }
        public Nullable<bool> IITMPensioner_f { get; set; }
        public Nullable<bool> EnhanceWithExtend_f { get; set; }
    }
}
