//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTSummarInternship
    {
        public int RCTSummarInternshipId { get; set; }
        public string FileNo { get; set; }
        public Nullable<System.DateTime> ReferenceletterDate { get; set; }
        public string RollNo { get; set; }
        public Nullable<int> ProfessionalType { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> Sex { get; set; }
        public string ContactNo { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<bool> IsSameasAbove { get; set; }
        public string Course { get; set; }
        public string OtherCourse { get; set; }
        public Nullable<int> YearofStudy { get; set; }
        public string CollegeName { get; set; }
        public Nullable<decimal> Stipend { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<System.DateTime> AppointmentStartdate { get; set; }
        public Nullable<System.DateTime> AppointmentEnddate { get; set; }
        public string Status { get; set; }
        public Nullable<int> CrtdUser { get; set; }
        public Nullable<System.DateTime> CrtdTs { get; set; }
        public Nullable<int> UptdUser { get; set; }
        public Nullable<System.DateTime> UptdTs { get; set; }
        public Nullable<int> RollSqNbr { get; set; }
        public Nullable<bool> IsConsentletterAttached { get; set; }
        public string ConsentDocumentAttachedName { get; set; }
        public string ConsentDocumentName { get; set; }
    }
}
