//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTProfessionalTax
    {
        public int ProfessionalTaxId { get; set; }
        public Nullable<decimal> MonthySalary35 { get; set; }
        public Nullable<decimal> MonthySalary35to5 { get; set; }
        public Nullable<decimal> MonthySalary5to75 { get; set; }
        public Nullable<decimal> MonthySalary75to10 { get; set; }
        public Nullable<decimal> MonthySalary10to12 { get; set; }
        public Nullable<decimal> MonthySalaryAbove12 { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<int> CrtdUser { get; set; }
        public Nullable<System.DateTime> CrtdTs { get; set; }
        public Nullable<int> UptdUser { get; set; }
        public Nullable<System.DateTime> UptdTs { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsCurrentVersion { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
