//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRCTSTEEducationDetail_09Apr2021
    {
        public Nullable<int> STEEducationDetailID { get; set; }
        public string FileNo { get; set; }
        public string Qualification { get; set; }
        public Nullable<int> QualifiCationID { get; set; }
        public Nullable<int> DisciplineID { get; set; }
        public string UniversityorInstitution { get; set; }
        public Nullable<int> YearOfPassing { get; set; }
        public Nullable<decimal> Marks { get; set; }
        public Nullable<int> DivisionClassObtained { get; set; }
        public Nullable<int> DocumentFilePath { get; set; }
        public Nullable<int> Remarks { get; set; }
        public Nullable<int> CrtdUser { get; set; }
        public Nullable<int> CrtdTs { get; set; }
        public Nullable<int> UptdUser { get; set; }
        public Nullable<int> UptdTs { get; set; }
        public Nullable<bool> isCurrentVersion { get; set; }
        public Nullable<int> FileName { get; set; }
        public Nullable<int> MarkType { get; set; }
        public Nullable<bool> isActiveNow { get; set; }
    }
}
