//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpecialApprovalDoc
    {
        public int ProjectSpecialApprovalId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public string DocumentName { get; set; }
        public string DocumentRemark { get; set; }
        public string Status { get; set; }
        public string AttachmentPath { get; set; }
        public Nullable<System.DateTime> Crt_TS { get; set; }
    }
}
