//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalaryAgencyComponentLog
    {
        public int LogId { get; set; }
        public Nullable<int> SalaryAgencyId { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public Nullable<decimal> ComponentValue { get; set; }
        public Nullable<System.DateTime> Created_TS { get; set; }
        public Nullable<int> Created_Id { get; set; }
        public Nullable<int> UpdateSeqNo { get; set; }
        public Nullable<decimal> OldComponentValue { get; set; }
    }
}
