//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUCExpenditureDetail
    {
        public int UCExpenditureDetailId { get; set; }
        public Nullable<int> HeadId { get; set; }
        public Nullable<decimal> CommitmentTreatedAsExp { get; set; }
        public Nullable<int> UCId { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ExpenditureAsPerBook { get; set; }
        public Nullable<decimal> ExpenditureAsPerUC { get; set; }
        public Nullable<decimal> UCCommitmentWithdrawn { get; set; }
        public Nullable<decimal> UCCommitmentUtilized { get; set; }
        public Nullable<decimal> UCCommitmentUnutilized { get; set; }
    }
}
