//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblYearwiseSummary
    {
        public int YearwiseSummaryId { get; set; }
        public Nullable<int> FinYear { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectNumber { get; set; }
        public string PIName { get; set; }
        public Nullable<int> PIId { get; set; }
        public Nullable<decimal> ExpAmount { get; set; }
        public Nullable<decimal> UCExpAmount { get; set; }
        public Nullable<decimal> OpeningBal { get; set; }
        public Nullable<decimal> UCOpeningBal { get; set; }
        public Nullable<decimal> GrantReceived { get; set; }
        public Nullable<decimal> ClosingBal { get; set; }
        public Nullable<decimal> UCClosingBal { get; set; }
    }
}
