//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblYearwiseSummaryDetail
    {
        public int YearwiseSummaryDetailId { get; set; }
        public Nullable<int> YearwiseSummaryId { get; set; }
        public string HeadName { get; set; }
        public Nullable<int> HeadId { get; set; }
        public Nullable<decimal> ExpAmount { get; set; }
        public Nullable<decimal> UCExpAmount { get; set; }
        public Nullable<int> FinYear { get; set; }
        public Nullable<int> ProjectId { get; set; }
    }
}
