//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp
    {
        public Nullable<int> osgid { get; set; }
        public Nullable<int> QualificationId { get; set; }
        public Nullable<int> DisciplineId { get; set; }
        public string UniversityorInstitution { get; set; }
        public Nullable<int> YearOfPassing { get; set; }
        public Nullable<decimal> Marks { get; set; }
        public Nullable<int> DivisionClassObtained { get; set; }
        public Nullable<int> DocumentFile { get; set; }
        public string remarks { get; set; }
        public int crt { get; set; }
        public System.DateTime ctdd { get; set; }
        public Nullable<int> UptdUser { get; set; }
        public Nullable<int> UptdTs { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> isCurrentVersion { get; set; }
        public Nullable<int> FileName { get; set; }
        public Nullable<int> DocumentFilePath { get; set; }
        public Nullable<int> MarkType { get; set; }
    }
}
