//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_taxUpdate
    {
        public string PaymentId { get; set; }
        public int AnnualSalary { get; set; }
        public int AnnualTaxableSalary { get; set; }
    }
}
