//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_AgencyWiseProposal
    {
        public string DepartmentName { get; set; }
        public string FirstName { get; set; }
        public string ProposalTitle { get; set; }
        public string AgencyCode { get; set; }
        public Nullable<decimal> BasicValue { get; set; }
        public Nullable<decimal> ApplicableTax { get; set; }
        public Nullable<System.DateTime> Crtd_TS { get; set; }
        public string ProposalNumber { get; set; }
        public int ProposalId { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public string MonthYear { get; set; }
    }
}
