//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AllocationWiseCommitment
    {
        public string ProjectNumber { get; set; }
        public string ProjectType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public Nullable<decimal> SanctionValue { get; set; }
        public Nullable<decimal> BaseValue { get; set; }
        public string SanctionOrderNumber { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<decimal> Comm_Staff { get; set; }
        public Nullable<decimal> Comm_Consumables { get; set; }
        public Nullable<decimal> Comm_Contingencies { get; set; }
        public Nullable<decimal> Comm_Travel { get; set; }
        public Nullable<decimal> Comm_Component { get; set; }
        public Nullable<decimal> Comm_Overheads { get; set; }
        public Nullable<decimal> Comm_Equipment { get; set; }
        public Nullable<decimal> Comm_Others { get; set; }
        public Nullable<decimal> Comm_PublicationMonograph { get; set; }
        public Nullable<decimal> Comm_WorkshopSymposium { get; set; }
        public Nullable<decimal> Comm_ScientificSocialResponsibility { get; set; }
        public Nullable<decimal> Comm_IPFee { get; set; }
        public Nullable<decimal> Comm_Miscellaneous { get; set; }
        public Nullable<decimal> Comm_FieldTestingDemoTraining { get; set; }
        public Nullable<decimal> Comm_Software { get; set; }
        public Nullable<decimal> Comm_ConsumablesTravelContingencies { get; set; }
        public Nullable<decimal> Comm_ConsumablesTravel { get; set; }
        public Nullable<decimal> Comm_Refundofunspentbalance { get; set; }
        public Nullable<decimal> Comm_Refundofunspentinterest { get; set; }
        public Nullable<decimal> Comm_FieldWork { get; set; }
        public Nullable<decimal> Comm_EquipmentandStudyMaterial { get; set; }
        public Nullable<decimal> Comm_PublicationofReport { get; set; }
        public Nullable<decimal> Comm_OverheadsContingencies { get; set; }
        public Nullable<decimal> Comm_Consultants { get; set; }
        public Nullable<decimal> Comm_ConsumablesandAccessories { get; set; }
        public Nullable<decimal> Comm_ConsultancyFees { get; set; }
        public Nullable<decimal> Comm_ConsumablesTravelContingenciesOtherCost { get; set; }
        public Nullable<decimal> Comm_UnspentBalance { get; set; }
        public Nullable<decimal> Comm_InterestRefund { get; set; }
        public Nullable<decimal> Comm_Distribution { get; set; }
        public Nullable<decimal> Comm_Outsourcing { get; set; }
    }
}
