//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Adminsalary
    {
        public string ComponentName { get; set; }
        public string PayeeCategory { get; set; }
        public string Name { get; set; }
        public string BillNumber { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string MonthandYear { get; set; }
        public Nullable<int> Category { get; set; }
        public int id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    }
}
