//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AnnualAccounts
    {
        public Nullable<int> ProjectId { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> RunningTotal { get; set; }
        public Nullable<System.DateTime> DateOfTransaction { get; set; }
        public string RefNo { get; set; }
        public string TransType { get; set; }
        public string Code { get; set; }
        public string FunctionName { get; set; }
        public string Category { get; set; }
        public string CommitmentNumber { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> OB { get; set; }
        public Nullable<decimal> Staff { get; set; }
        public Nullable<decimal> Consumables { get; set; }
        public Nullable<decimal> Contingencies { get; set; }
        public Nullable<decimal> Travel { get; set; }
        public Nullable<decimal> Component { get; set; }
        public Nullable<decimal> Overheads { get; set; }
        public Nullable<decimal> Equipment { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<decimal> Miscellaneous { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public Nullable<decimal> sanctionValue { get; set; }
        public string SanctionOrderNumber { get; set; }
        public string ProjectTitle { get; set; }
        public string PIName { get; set; }
        public int ProjectTypeId { get; set; }
        public Nullable<int> ProjectClassification { get; set; }
        public string SponProjectCategory { get; set; }
        public Nullable<int> PIid { get; set; }
        public string PIDepartment { get; set; }
        public string ProjectSchemeCode { get; set; }
        public string AgencyName { get; set; }
        public string ProposalNumber { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public string AgencyCode { get; set; }
        public string ProjectClass { get; set; }
        public string ProjectStatus { get; set; }
        public Nullable<decimal> UnspentBalance { get; set; }
        public Nullable<decimal> InterestRefund { get; set; }
    }
}
