//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AgencyMaster
    {
        public string AgencyCountry { get; set; }
        public string IndianCategory { get; set; }
        public string GSTCategory { get; set; }
        public string Country { get; set; }
        public int AgencyId { get; set; }
        public string AgencyName { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public string ContactEmail { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> Crtd_TS { get; set; }
        public string Reason { get; set; }
        public string AgencyCode { get; set; }
        public string GSTIN { get; set; }
        public string TAN { get; set; }
        public string PAN { get; set; }
        public string IndiaState { get; set; }
        public string StateCode { get; set; }
        public string ProjectType { get; set; }
        public string CompanyType { get; set; }
        public string GovermentAgencyTypes { get; set; }
        public string District { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string AgencyRegisterName { get; set; }
    }
}
