//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AccountsMonthlyReceiptReport
    {
        public string ProjectType { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public string ProjectNumber { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
    }
}
