//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AdhocEmployees
    {
        public string paybill { get; set; }
        public string FileNo { get; set; }
        public string OldFileno { get; set; }
        public string NAME { get; set; }
        public string DEPARTMENT { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PROJECTNO { get; set; }
        public string commitmentNo { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> ExtensionDate { get; set; }
        public Nullable<System.DateTime> RelieveDate { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string BankName { get; set; }
        public string PAN { get; set; }
    }
}
