//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AgencyReport
    {
        public int InvoiceId { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string ProjectNumber { get; set; }
        public string TaxCategory { get; set; }
        public string ProjectType { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<decimal> TaxableValue { get; set; }
        public Nullable<decimal> CGSTRate { get; set; }
        public Nullable<decimal> CGSTAmount { get; set; }
        public Nullable<decimal> SGSTRate { get; set; }
        public Nullable<decimal> SGSTAmount { get; set; }
        public Nullable<decimal> IGSTRate { get; set; }
        public Nullable<decimal> IGSTAmount { get; set; }
        public Nullable<decimal> TotalTaxValue { get; set; }
        public Nullable<decimal> TotalInvoiceValue { get; set; }
        public Nullable<decimal> InvoiceValueinForeignCurrency { get; set; }
        public string CurrencyCode { get; set; }
        public string InvoiceStatus { get; set; }
        public string PIName { get; set; }
        public string TaxCode { get; set; }
        public string AgencyName { get; set; }
        public string AgencyCountry { get; set; }
        public string FinancialYear { get; set; }
        public string GSTIN { get; set; }
        public string PAN { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public Nullable<decimal> ReceiptValueinForeignCurrency { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> BankAmountDr { get; set; }
        public Nullable<decimal> TDSReceivable { get; set; }
        public Nullable<decimal> IGSTTDSReceivable { get; set; }
        public Nullable<decimal> BankCharges { get; set; }
        public Nullable<decimal> RoundoffDebit { get; set; }
        public Nullable<decimal> CreditNote { get; set; }
        public Nullable<System.DateTime> InvoicePostedDate { get; set; }
    }
}
