//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Bill
    {
        public Nullable<int> SourceReferenceNumber { get; set; }
        public string SourceType { get; set; }
        public string SourceNumber { get; set; }
        public string BillType { get; set; }
        public string ReferenceNumber { get; set; }
        public string BillStatus { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CreatedUser { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
