//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BOAExpenditure
    {
        public int BOAExpenseDetailId { get; set; }
        public Nullable<int> RefId { get; set; }
        public string ReferenceNumber { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> PayeeId { get; set; }
        public string PayeeType { get; set; }
        public Nullable<int> PayeeTypeId { get; set; }
        public string PayeeName { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string BillStatus { get; set; }
        public Nullable<decimal> TDSAmount { get; set; }
        public string BankHead { get; set; }
        public string ProjectNumber { get; set; }
        public string PayeeAccountNumber { get; set; }
        public string PayeeBank { get; set; }
        public string PayeeBankIFSC { get; set; }
        public string PAN { get; set; }
        public string GSTIN { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string PaymentStatus { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectType { get; set; }
        public Nullable<decimal> TDSBasicAmount { get; set; }
        public Nullable<int> TDSSectionId { get; set; }
        public string TDSSection { get; set; }
        public Nullable<int> BOAId { get; set; }
        public Nullable<int> BankHeadId { get; set; }
        public Nullable<decimal> TDSGST { get; set; }
        public string SchemeCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CashBookDate { get; set; }
        public Nullable<int> Posted_f { get; set; }
        public Nullable<decimal> TDSGSTBasicAmount { get; set; }
        public string CommitmentNo { get; set; }
        public string HeadName { get; set; }
        public string FunctionName { get; set; }
        public string ProjectSchemeCode { get; set; }
        public string ProjType { get; set; }
        public string ModeOfPayment { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public string vendorCode { get; set; }
        public string TravellerDetails { get; set; }
        public string TravelFromDate { get; set; }
        public string TravelToDate { get; set; }
        public string Place { get; set; }
        public string AdvanceValue { get; set; }
        public string Advancerefnumber { get; set; }
        public string Month { get; set; }
    }
}
