//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CashBokkDetails
    {
        public string PaymentType { get; set; }
        public string RefNumber { get; set; }
        public string BankName { get; set; }
        public string PayeeName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
    }
}
