//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_commitmentBookedvsAvail
    {
        public string CommitmentType { get; set; }
        public string CommitmentNumber { get; set; }
        public string ProjectNumber { get; set; }
        public string VendorName { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public Nullable<decimal> AdditionalCharge { get; set; }
        public string CommitmentStatus { get; set; }
        public string HeadName { get; set; }
        public Nullable<decimal> TotalBookedAmount { get; set; }
        public Nullable<decimal> AvailableBalance { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string Rem1 { get; set; }
        public string Rem2 { get; set; }
        public string PurchaseOrder { get; set; }
        public string AddOrCloseRemarks { get; set; }
        public Nullable<decimal> ForignCurrencyValue { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> CommCumulativebeforeAddition { get; set; }
        public Nullable<decimal> AdditionAmount { get; set; }
        public Nullable<decimal> ReversalAmount { get; set; }
        public Nullable<decimal> ClosedAmount { get; set; }
        public Nullable<decimal> BillsAllocated { get; set; }
        public string ItemDescription { get; set; }
        public string ProjType { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public string Subhead { get; set; }
    }
}
