//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CommitmentDetailReport
    {
        public string CommitmentType { get; set; }
        public string CommitmentNumber { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectType { get; set; }
        public string VendorName { get; set; }
        public Nullable<decimal> CommitmentAmount { get; set; }
        public Nullable<decimal> CommitmentBalance { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PONumber { get; set; }
        public string AttachmentName { get; set; }
        public string UserName { get; set; }
        public string BudgetHead { get; set; }
        public Nullable<decimal> BudgetHeadAmount { get; set; }
        public string Purpose { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<decimal> AvailableBalance { get; set; }
        public string PIName { get; set; }
        public string SanctionOrderNumber { get; set; }
        public string Currencycode { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public Nullable<decimal> AdditionalCharge { get; set; }
        public Nullable<decimal> ForignCurrencyValue { get; set; }
        public string TapalNo { get; set; }
        public string AddOrCloseRemarks { get; set; }
    }
}
