//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CorpusReport
    {
        public int DistributionId { get; set; }
        public string ReferenceNumber { get; set; }
        public string ProjectNumber { get; set; }
        public string AccountHead { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string MonthandYear { get; set; }
        public string Status { get; set; }
        public string TransactionType { get; set; }
        public string ProjType { get; set; }
        public string Bank { get; set; }
    }
}
