//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CommitmentTally
    {
        public int CommitmentId { get; set; }
        public string ProjectNumber { get; set; }
        public string CommitmentNumber { get; set; }
        public string HeadName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> CommitmentAmount { get; set; }
        public Nullable<decimal> CommitmentEnhancementAmount { get; set; }
        public Nullable<decimal> TotalCommitmentAmount { get; set; }
        public Nullable<decimal> AmountUtilized { get; set; }
        public Nullable<decimal> CommitmentWithDrawn { get; set; }
        public Nullable<decimal> AvailableBalance { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Difference { get; set; }
        public string Status { get; set; }
    }
}
