//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ClearancePayment
    {
        public string BillNumber { get; set; }
        public Nullable<System.DateTime> ReferencePoDAte { get; set; }
        public string ReferencePoNumber { get; set; }
        public string VendorName { get; set; }
        public string ProjectNumber { get; set; }
        public string CommitmentNumber { get; set; }
        public string ProjectType { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<decimal> BillTaxAMount { get; set; }
        public Nullable<decimal> CommitmentAMount { get; set; }
        public Nullable<decimal> ExpenseAmount { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> PaymentTDSAmount { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string BatchNumber { get; set; }
    }
}
