//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FixedDepositView
    {
        public string VoucherNumber { get; set; }
        public Nullable<System.DateTime> FDPostingDate { get; set; }
        public string ClosedVoucherNumber { get; set; }
        public Nullable<System.DateTime> FDCloseingDate { get; set; }
        public string AccountType { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string FDNumber { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> RateOfInterest { get; set; }
        public Nullable<decimal> NotionalInterest { get; set; }
        public Nullable<decimal> NotionalAmount { get; set; }
        public Nullable<decimal> MaturityAmount { get; set; }
        public string Status { get; set; }
        public string Period { get; set; }
        public string TermDeposit { get; set; }
        public Nullable<decimal> ActualInterestReceived { get; set; }
        public string Remarks { get; set; }
        public string ResonForclosure { get; set; }
    }
}
