//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form13
    {
        public string ProjectNumber { get; set; }
        public string ProjectType { get; set; }
        public string TAN { get; set; }
        public string PAN { get; set; }
        public string FundingAgencyName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public decimal sanctionValue { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
