//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_HeadwiseExpenditure
    {
        public int ProjectId { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectType { get; set; }
        public string SubCategory { get; set; }
        public string ProjectClassification { get; set; }
        public string EmployeeId { get; set; }
        public string PiName { get; set; }
        public Nullable<decimal> Staff { get; set; }
        public Nullable<decimal> Consumables { get; set; }
        public Nullable<decimal> Contingencies { get; set; }
        public Nullable<decimal> Travel { get; set; }
        public Nullable<decimal> Component { get; set; }
        public Nullable<decimal> Overheads { get; set; }
        public Nullable<decimal> Equipment { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<decimal> Miscellaneous { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
