//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_headcredit
    {
        public string HeadcreditNo { get; set; }
        public Nullable<System.DateTime> Expendituredate { get; set; }
        public Nullable<decimal> Totalvalue { get; set; }
        public Nullable<decimal> Projectamount { get; set; }
        public string ProjectNo { get; set; }
        public string HeadName { get; set; }
        public string Remarks { get; set; }
        public string GeneralRefNo { get; set; }
        public string BillRefNo { get; set; }
        public string Username { get; set; }
    }
}
