//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_HeadwisefundTransfer
    {
        public string TransferNumber { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CreditProjectNumber { get; set; }
        public string CreditProjectType { get; set; }
        public string DebitProjectNumber { get; set; }
        public string DebitProjectType { get; set; }
        public string DebitReason { get; set; }
        public string CreditReason { get; set; }
        public string Status { get; set; }
        public string UserName { get; set; }
    }
}
