//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ITTDSTmpReport
    {
        public string FunctionName { get; set; }
        public string ReferenceNumber { get; set; }
        public string Name { get; set; }
        public string PAN { get; set; }
        public string BillStatus { get; set; }
        public string CreditBankName { get; set; }
        public string TDSHead { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string Require { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public string TDSPaymentNumber { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectType { get; set; }
    }
}
