//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_imprestoverall
    {
        public string ImprestAccountNumber { get; set; }
        public string FacultyName { get; set; }
        public string InstituteID { get; set; }
        public string ImprestNumber { get; set; }
        public Nullable<System.DateTime> ImprestCreatedTS { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ImprestTotalValue { get; set; }
        public Nullable<decimal> EnhancedValue { get; set; }
        public string ImprestCloseNumber { get; set; }
        public Nullable<System.DateTime> ImprestCloseTS { get; set; }
    }
}
