//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_IMPReport
    {
        public string ImprestNumber { get; set; }
        public string PINAME { get; set; }
        public string ImprestACNumber { get; set; }
        public Nullable<decimal> EXISTINGIMPRESTVALUE { get; set; }
        public decimal Enhancevalue { get; set; }
        public Nullable<decimal> ImprestTotalValue { get; set; }
        public string Status { get; set; }
    }
}
