//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_InstituteSalary
    {
        public string InstituteSalaryPaymentNumber { get; set; }
        public string MonthandYear { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string RefBillNumber { get; set; }
        public string PaybillNo { get; set; }
        public Nullable<decimal> HonSalary { get; set; }
        public Nullable<decimal> DisSalary { get; set; }
        public Nullable<decimal> MdySalary { get; set; }
        public Nullable<decimal> FssSalary { get; set; }
        public int InstituteSalaryPaymentId { get; set; }
        public string Type { get; set; }
    }
}
