//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ITC
    {
        public int Id { get; set; }
        public string BillType { get; set; }
        public string RefNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string VendorName { get; set; }
        public string GSTIN { get; set; }
        public string HSNSAC { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public string CreditBankName { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string UserName { get; set; }
        public string BatchNumber { get; set; }
        public string ProjectNumber { get; set; }
        public long RowNumber { get; set; }
        public string TransactionTypeCode { get; set; }
    }
}
