//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ICSRB2B
    {
        public string GSTIN { get; set; }
        public string ReceiverName { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> TotalInvoiceValue { get; set; }
        public string PlaceOfSupply { get; set; }
        public string ReverseCharge { get; set; }
        public string ApplicableOfTaxRate { get; set; }
        public string InvoiceType { get; set; }
        public string ECommerceGSTIN { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> TaxableValue { get; set; }
        public string CessAmount { get; set; }
        public string SACcode { get; set; }
        public Nullable<decimal> CGSTAmount { get; set; }
        public Nullable<decimal> SGSTAmount { get; set; }
        public Nullable<decimal> IGSTAmount { get; set; }
    }
}
