//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ITCVerified
    {
        public string RefNumber { get; set; }
        public string VendorName { get; set; }
        public string GSTIN { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string Interstate { get; set; }
        public string GSTOffsetNumber { get; set; }
        public string Offset { get; set; }
        public int GSTCreditDetailsId { get; set; }
        public string ProjectNo { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
    }
}
