//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_LCAmmendmentReport
    {
        public string ReferenceNumber { get; set; }
        public Nullable<System.DateTime> AmmendmentDate { get; set; }
        public string ProjectNumber { get; set; }
        public string PONumber { get; set; }
        public string CommitmentNumber { get; set; }
        public string IssuingBankAccountNumber { get; set; }
        public decimal PaymentAmount { get; set; }
        public string PlaceofExpiry { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string AdvisingBank { get; set; }
        public string AdvisingBankBranch { get; set; }
        public string AdvisingBankAddress { get; set; }
        public string AdvisingBankSwiftorIFSC { get; set; }
        public string Beneficiary { get; set; }
        public string PortorAirportofDeparture { get; set; }
        public string PortorAirportofDestination { get; set; }
        public Nullable<System.DateTime> DateofShipment { get; set; }
        public string DescriptionofGoodsandService { get; set; }
        public string ProformaInvoiceNumber { get; set; }
        public Nullable<System.DateTime> ProformaInvoiceDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    }
}
