//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NegativeBalanceReport
    {
        public string ReferenceNumber { get; set; }
        public string ProjectNumber { get; set; }
        public string PIName { get; set; }
        public string ProjectType { get; set; }
        public Nullable<decimal> ClaimAmount { get; set; }
        public Nullable<decimal> NegativeBalanceAmount { get; set; }
        public Nullable<decimal> ReceiptAdjustmentAmount { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public int ProjectTypeId { get; set; }
        public Nullable<int> ProjectClassification { get; set; }
        public string SponProjectCategory { get; set; }
        public string PIDepartment { get; set; }
        public Nullable<int> PiId { get; set; }
        public string ProjectSchemeCode { get; set; }
        public string AgencyName { get; set; }
        public Nullable<System.DateTime> ProjectStartDate { get; set; }
        public Nullable<System.DateTime> ProjectClosureDate { get; set; }
        public string ProposalNumber { get; set; }
        public string ReasonForClose { get; set; }
        public string RemarksForClose { get; set; }
        public string AgencyCode { get; set; }
        public string ProjectClass { get; set; }
    }
}
