//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OfficeMonthlyEnhancementReport
    {
        public string ProjectType { get; set; }
        public string ProjectNumber { get; set; }
        public string PIDepartment { get; set; }
        public Nullable<decimal> EnhancedSanctionValue { get; set; }
        public Nullable<decimal> EnhancedTaxValue { get; set; }
        public Nullable<System.DateTime> CrtsTS { get; set; }
    }
}
