//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OverallSalaryITPT
    {
        public string SalaryType { get; set; }
        public string TypeOfBill { get; set; }
        public string PaymentNo { get; set; }
        public string PaymentMonthyear { get; set; }
        public string Bank { get; set; }
        public Nullable<decimal> IT { get; set; }
        public Nullable<decimal> PT { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> MA { get; set; }
        public Nullable<decimal> InstituteHospital { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
        public Nullable<decimal> OtherAllowance { get; set; }
        public Nullable<decimal> GrossTotal { get; set; }
    }
}
