//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OfficeReportChanges
    {
        public string FinancialYear { get; set; }
        public string ProjectType { get; set; }
        public string ProjectNumber { get; set; }
        public string PrincipalInvestigator { get; set; }
        public string DepOfPrincipalInvestigator { get; set; }
        public string ProjectCoPi { get; set; }
        public string ProjectTitle { get; set; }
        public string AgencyCode { get; set; }
        public string AgencyName { get; set; }
        public string SanctionOrderNumber { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> OriginalCloseDate { get; set; }
        public Nullable<System.DateTime> ExtendedDate { get; set; }
        public Nullable<decimal> BaseValue { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<decimal> SanctionValue { get; set; }
        public Nullable<decimal> TotalEnhancedValue { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public string AgencyRegisterAddress { get; set; }
        public string GSTIN { get; set; }
        public string PAN { get; set; }
        public string TAN { get; set; }
        public string TaxserviceGST { get; set; }
        public string StateOfFundingAgency { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public string FundingTypeName { get; set; }
        public string AgencyType { get; set; }
        public string ProjectClassification { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string CreatedUserName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ProjectCoPiID { get; set; }
        public string ProjectCoPiName { get; set; }
        public string SchemeCode { get; set; }
        public string ForeignState { get; set; }
        public string ForeignCountry { get; set; }
        public string CurrencyType { get; set; }
        public Nullable<decimal> ForeignCurrencyValue { get; set; }
        public Nullable<decimal> Convertionvalue { get; set; }
        public string SchemeName { get; set; }
        public string DomainName { get; set; }
    }
}
