//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OthersTapalReport
    {
        public int TapalId { get; set; }
        public string TapalNo { get; set; }
        public Nullable<System.DateTime> TapalDate { get; set; }
        public Nullable<int> PIId { get; set; }
        public string PINAME { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<System.DateTime> FinalReceiverDate { get; set; }
        public Nullable<int> ReferenceNumber { get; set; }
        public string Notes { get; set; }
        public Nullable<int> DateDifferenceInDays { get; set; }
    }
}
