//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OverallProjectReport
    {
        public string ProjectNumber { get; set; }
        public string SanctionOrderNumber { get; set; }
        public string ProjectType { get; set; }
        public string PiName { get; set; }
        public string CoPI { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<decimal> BaseValue { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public string AgencyName { get; set; }
        public string AgencyRegisterAddress { get; set; }
        public string AgencyCode { get; set; }
        public string GSTIN { get; set; }
        public string PAN { get; set; }
        public string TAN { get; set; }
        public string ContactPersonname { get; set; }
        public string ContactPersonEmail { get; set; }
        public string Taxservice { get; set; }
        public string StateOfFundingAgency { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CreatedUserName { get; set; }
        public string Status { get; set; }
        public string EmployeeId { get; set; }
        public string Remarks { get; set; }
        public string FundingTypeName { get; set; }
    }
}
