//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PurchaseIndentandInvoice
    {
        public int TapalId { get; set; }
        public string TapalNo { get; set; }
        public Nullable<System.DateTime> TapalEntryDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> OutwardDate { get; set; }
        public string PurUser { get; set; }
        public Nullable<System.DateTime> PurUserReceivedDate { get; set; }
        public Nullable<System.DateTime> Query { get; set; }
        public Nullable<System.DateTime> WaiverApproval { get; set; }
        public string AccountsDAName { get; set; }
        public Nullable<System.DateTime> AccountsDADate { get; set; }
        public Nullable<System.DateTime> puraud { get; set; }
        public Nullable<System.DateTime> purcommitee { get; set; }
        public Nullable<System.DateTime> purdean { get; set; }
        public Nullable<System.DateTime> Director { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string ReferenceNumber { get; set; }
    }
}
