//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProjectProposal
    {
        public string ProposalNumber { get; set; }
        public string FirstName { get; set; }
        public string ProposalTitle { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<System.DateTime> InwardDate { get; set; }
        public Nullable<System.DateTime> Crtd_TS { get; set; }
        public Nullable<System.DateTime> SourceEmailDate { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public int ProposalId { get; set; }
        public Nullable<int> Noofdays { get; set; }
    }
}
