//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PendingforInvoiceApproval
    {
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Invoicetype { get; set; }
        public string ProjectNumber { get; set; }
        public string EmployeeName { get; set; }
        public string TaxCode { get; set; }
        public string DescriptionofServices { get; set; }
        public Nullable<decimal> TaxableValue { get; set; }
        public Nullable<decimal> CGSTRate { get; set; }
        public Nullable<decimal> CGSTAmount { get; set; }
        public decimal SGSTRate { get; set; }
        public Nullable<decimal> SGSTAmount { get; set; }
        public Nullable<decimal> IGSTRate { get; set; }
        public Nullable<decimal> IGSTAmount { get; set; }
        public Nullable<decimal> TotalTaxValue { get; set; }
        public Nullable<decimal> TotalInvoiceValue { get; set; }
        public string AgencyRegName { get; set; }
        public string CommunicationAddress { get; set; }
        public string AgencyRegGSTIN { get; set; }
        public string AgencyRegTAN { get; set; }
        public string AgencyDistrict { get; set; }
        public Nullable<int> AgencyPincode { get; set; }
        public string StateName { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> InvoiceValueinForeignCurrency { get; set; }
    }
}
