//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PFMSPayeewiseExpenditureReport
    {
        public string ReferenceNumber { get; set; }
        public string PayeeType { get; set; }
        public string PayeeName { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string BillStatus { get; set; }
        public Nullable<decimal> TDSAmount { get; set; }
        public string BankHead { get; set; }
        public string ProjectNumber { get; set; }
        public string PayeeAccountNumber { get; set; }
        public string PayeeBank { get; set; }
        public string PayeeBankIFSC { get; set; }
        public string GSTIN { get; set; }
        public string PaymentStatus { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> TDSBasicAmount { get; set; }
        public string TDSSection { get; set; }
        public Nullable<decimal> TDSGST { get; set; }
        public string Remarks { get; set; }
        public string CommitmentNo { get; set; }
        public string HeadName { get; set; }
        public string FunctionName { get; set; }
        public string ProjectSchemeCode { get; set; }
        public string ProjType { get; set; }
        public string ModeOfPayment { get; set; }
        public string vendorCode { get; set; }
        public string TravellerDetails { get; set; }
        public string TravelFromDate { get; set; }
        public string TravelToDate { get; set; }
        public string AdvanceValue { get; set; }
        public string Advancerefnumber { get; set; }
        public Nullable<System.DateTime> CashBookDate { get; set; }
    }
}
