//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProjecReportForSP
    {
        public string ProjectType { get; set; }
        public string ProjectNumber { get; set; }
        public string SanctionOrderNumber { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<decimal> SanctionValue { get; set; }
        public string Status { get; set; }
        public string PIName { get; set; }
        public int ProjectId { get; set; }
        public int ProjectTypeid { get; set; }
        public Nullable<int> ProjectClassification { get; set; }
        public string SponProjectCategory { get; set; }
        public string PIDepartment { get; set; }
        public Nullable<int> PIid { get; set; }
        public string ProjectSchemeCode { get; set; }
        public string AgencyName { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public string AgencyCode { get; set; }
        public Nullable<int> ProjectTypeInt { get; set; }
        public string ProposalNumber { get; set; }
        public string ProjectClass { get; set; }
        public string ProjectStatus { get; set; }
    }
}
