//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PurchaseTapalMaster
    {
        public int TapalId { get; set; }
        public int TapalWorkflowId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TapalNo { get; set; }
        public string UserName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> CreatedTS { get; set; }
        public Nullable<int> TapalAction { get; set; }
    }
}
