//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProjectDailyReport
    {
        public string ProjectType { get; set; }
        public string Year { get; set; }
        public string ProjectNumber { get; set; }
        public string AgencyName { get; set; }
        public string SanctionOrderNumber { get; set; }
        public string PIDEP { get; set; }
        public string ProjectCoPiDep { get; set; }
        public string CoPiID { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<decimal> SanctionValue { get; set; }
        public string ProposalNumber { get; set; }
        public string Status { get; set; }
        public int ProjectId { get; set; }
        public string PIName { get; set; }
        public string ReportClassification { get; set; }
        public string AgencyCode { get; set; }
        public string ProjectClass { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
