//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProjectCount
    {
        public int RefId { get; set; }
        public string RefNumber { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ProjectCount { get; set; }
        public string TransactionTypeCode { get; set; }
        public string FunctionName { get; set; }
        public int ProjectId { get; set; }
    }
}
