//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProjectOBExp
    {
        public Nullable<int> ProjectId { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectType { get; set; }
        public string HeadName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public Nullable<decimal> sanctionValue { get; set; }
        public string SanctionOrderNumber { get; set; }
        public string ProjectTitle { get; set; }
        public string PIName { get; set; }
    }
}
