//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PurchaseCommitmentReport
    {
        public string ProjectNumber { get; set; }
        public string ProjectType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public string PurchaseOrder { get; set; }
        public string Invoicevalue { get; set; }
        public string Tax { get; set; }
        public string Others { get; set; }
        public string CommitmentNumber { get; set; }
        public Nullable<decimal> CommitmentAmount { get; set; }
        public Nullable<decimal> Expenditure { get; set; }
        public Nullable<decimal> CommitmentBalance { get; set; }
        public string Remarks { get; set; }
        public string CommitmentStatus { get; set; }
    }
}
