//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProjectwiseAllocationYearWise
    {
        public string ProjectNumber { get; set; }
        public string ProjectType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string TaxStatus { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<decimal> SanctionValue { get; set; }
        public Nullable<decimal> BaseValue { get; set; }
        public string SanctionOrderNumber { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<decimal> Allo_Staff { get; set; }
        public Nullable<decimal> Allo_Consumables { get; set; }
        public Nullable<decimal> Allo_Contingencies { get; set; }
        public Nullable<decimal> Allo_Travel { get; set; }
        public Nullable<decimal> Allo_Component { get; set; }
        public Nullable<decimal> Allo_Overheads { get; set; }
        public Nullable<decimal> Allo_Equipment { get; set; }
        public Nullable<decimal> Allo_Others { get; set; }
        public Nullable<decimal> Allo_PublicationMonograph { get; set; }
        public Nullable<decimal> Allo_WorkshopSymposium { get; set; }
        public Nullable<decimal> Allo_ScientificSocialResponsibility { get; set; }
        public Nullable<decimal> Allo_IPFee { get; set; }
        public Nullable<decimal> Allo_Miscellaneous { get; set; }
        public Nullable<decimal> Allo_FieldTestingDemoTraining { get; set; }
        public Nullable<decimal> Allo_Software { get; set; }
        public Nullable<decimal> Allo_ConsumablesTravelContingencies { get; set; }
        public Nullable<decimal> Allo_ConsumablesTravel { get; set; }
        public Nullable<decimal> Allo_Refundofunspentbalance { get; set; }
        public Nullable<decimal> Allo_Refundofunspentinterest { get; set; }
        public Nullable<decimal> Allo_FieldWork { get; set; }
        public Nullable<decimal> Allo_EquipmentandStudyMaterial { get; set; }
        public Nullable<decimal> Allo_PublicationofReport { get; set; }
        public Nullable<decimal> Allo_OverheadsContingencies { get; set; }
        public Nullable<decimal> Allo_Consultants { get; set; }
        public Nullable<decimal> Allo_ConsumablesandAccessories { get; set; }
        public Nullable<decimal> Allo_ConsultancyFees { get; set; }
        public Nullable<decimal> Allo_ConsumablesTravelContingenciesOtherCost { get; set; }
        public Nullable<decimal> Allo_UnspentBalance { get; set; }
        public Nullable<decimal> Allo_InterestRefund { get; set; }
        public Nullable<decimal> Allo_Distribution { get; set; }
        public Nullable<decimal> Allo_Outsourcing { get; set; }
        public string PIname { get; set; }
        public int ProjectId { get; set; }
        public int ProjectTypeId { get; set; }
        public Nullable<int> ProjectClassification { get; set; }
        public string SponProjectCategory { get; set; }
        public Nullable<int> PIid { get; set; }
        public string PIDepartment { get; set; }
        public string ProjectSchemeCode { get; set; }
        public string AgencyName { get; set; }
        public string ProposalNumber { get; set; }
        public string ProjectStatus { get; set; }
    }
}
