//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ReceiptReport
    {
        public string ReceiptCategory { get; set; }
        public string ReceiptType { get; set; }
        public string ReceiptNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<decimal> BankAmountDr { get; set; }
        public string Projecttype { get; set; }
        public string ProjectClassification { get; set; }
        public string ProjectSubType { get; set; }
        public string BankName { get; set; }
        public string PiName { get; set; }
        public string PIDepartment { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public Nullable<decimal> ReceiptOverheadValue { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public string AgencyName { get; set; }
        public string ModeOfPayment { get; set; }
        public string TransactionNumber { get; set; }
        public string TransactionDate { get; set; }
        public string TransactionBankName { get; set; }
        public Nullable<decimal> TDSReceivable { get; set; }
        public Nullable<decimal> IGSTTDSReceivable { get; set; }
        public Nullable<decimal> CGSTTDSReceivable { get; set; }
        public Nullable<decimal> SGSTTDSReceivable { get; set; }
        public Nullable<decimal> BankCharges { get; set; }
        public Nullable<decimal> RoundoffDebit { get; set; }
        public string SourceProjectNumber { get; set; }
        public string SourceBillNumber { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> ReceiptValueinForeignCurrency { get; set; }
        public string CurrencyCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Projectid { get; set; }
        public string ProjectTitle { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Posted_f { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<decimal> ReceiptAmountExcludedTax { get; set; }
    }
}
