//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTExtentesionandEnhancement
    {
        public int OrderId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Status { get; set; }
        public string EmployeeNo { get; set; }
        public string Category { get; set; }
        public string CandidateName { get; set; }
        public string CodeDescription { get; set; }
        public string ProjectNumber { get; set; }
    }
}
