//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTDesignation
    {
        public string CodeValDetail { get; set; }
        public string DesignationCode { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> PayStructureMinMum { get; set; }
        public Nullable<decimal> PayStructureMaximum { get; set; }
        public Nullable<bool> HRA { get; set; }
        public Nullable<bool> Medical { get; set; }
        public Nullable<int> Status { get; set; }
        public int DesignationId { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> SalaryLevel { get; set; }
    }
}
