//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTSTERelievingReport
    {
        public string EMPLOYEE_ID { get; set; }
        public string NAME { get; set; }
        public string DESIGNATION { get; set; }
        public string PROJECT_NO { get; set; }
        public Nullable<System.DateTime> RELIEVING_ON { get; set; }
        public string NO_DUES_IF_ANY { get; set; }
        public Nullable<System.DateTime> LOG_TIME { get; set; }
        public string CREATED_BY { get; set; }
        public string Requested_by { get; set; }
        public string MS_PHD_COURSE { get; set; }
        public string Request_Reference { get; set; }
        public string Request_Reference_Number { get; set; }
        public string MODE_OF_RELIEVING { get; set; }
        public Nullable<System.DateTime> REQUEST_RECEIVED_DATE { get; set; }
        public Nullable<System.DateTime> COMPLETED__DATE { get; set; }
        public string COMPLETED_BY { get; set; }
        public Nullable<System.DateTime> COMMITMENT_WITHDRAWAL_DATE { get; set; }
    }
}
