//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTOngoingRelieving
    {
        public string EmployeersID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Gender { get; set; }
        public string Caste { get; set; }
        public string PANNo { get; set; }
        public string AadhaarNumber { get; set; }
        public string Status { get; set; }
        public string TypeofAppointment { get; set; }
        public string Designation { get; set; }
        public string PIName { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentCode { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<System.DateTime> RelieveDate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public string MedicalType { get; set; }
        public string Qualification { get; set; }
        public string IITMPensionerorCSIRStaff { get; set; }
        public string CSIRStaffPayMode { get; set; }
        public string MsPhdType { get; set; }
        public string RollNo { get; set; }
        public string PayType { get; set; }
        public string StaffCategory { get; set; }
        public string PhysicallyChallenged { get; set; }
        public string EmployeeWorkplace { get; set; }
        public string BankName { get; set; }
        public string BankAccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string RequestreceivedfromPI { get; set; }
        public string Othergovtagencyrollno { get; set; }
        public string Created_By { get; set; }
        public string AppointmentType { get; set; }
    }
}
