//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTOutsourcingParttime
    {
        public string VendorName { get; set; }
        public string Projecttype { get; set; }
        public string ProjectNumber { get; set; }
        public string CandidateName { get; set; }
        public string DesignationName { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> CostToProject { get; set; }
        public string ProjectTitle { get; set; }
        public string DepartmentName { get; set; }
        public string PIName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
