//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTDataParttime
    {
        public string EmployeeNo { get; set; }
        public string ProjectType { get; set; }
        public string ProjectNumber { get; set; }
        public string CandidateName { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> Pay { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public string Title { get; set; }
        public string DepartmentName { get; set; }
        public string CoordinatorName { get; set; }
    }
}
