//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTApprovedApplicationsReport
    {
        public long RowNumber { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string Category { get; set; }
        public string CandidateName { get; set; }
        public string TypeofAppointment { get; set; }
        public string PostRecommended { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<System.DateTime> AppointmentStartdate { get; set; }
        public Nullable<System.DateTime> AppointmentEnddate { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public string ApplicationType { get; set; }
        public string PIName { get; set; }
        public string CommiteeApproveName { get; set; }
        public string CheckList { get; set; }
    }
}
