//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTDeviationDetails
    {
        public long RowNumber { get; set; }
        public Nullable<int> appid { get; set; }
        public string apptype { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string Designation { get; set; }
        public Nullable<int> DeviationCheckListId { get; set; }
        public string CheckList { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public string ActualNorms { get; set; }
        public string DeviationNorms { get; set; }
        public Nullable<bool> isCurrentVersion { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string OrderType { get; set; }
    }
}
