//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTOSGExtensionEnhancementReport
    {
        public string EMPLOYEE_ID { get; set; }
        public string NAME { get; set; }
        public string EMPL_TYPE { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<System.DateTime> EXISTING_FROM { get; set; }
        public Nullable<System.DateTime> EXISTING_TO { get; set; }
        public decimal PREVIOUS_BASIC_PAY { get; set; }
        public Nullable<decimal> PREVIOUS_GROSS_PAY { get; set; }
        public string PROJECT_NO_ { get; set; }
        public string Project_details { get; set; }
        public string COMMITMENT_NO_ { get; set; }
        public Nullable<System.DateTime> FROM { get; set; }
        public Nullable<System.DateTime> TO { get; set; }
        public Nullable<System.DateTime> DATE_OF_INCREMENT { get; set; }
        public Nullable<decimal> YEARLY_INCREMENT { get; set; }
        public Nullable<decimal> CURRENT_BASIC_SALARY { get; set; }
        public Nullable<decimal> CURRENT_GROSS_PAY { get; set; }
        public string PF_Eligiblity { get; set; }
        public string ESIC_Eligiblity { get; set; }
        public Nullable<System.DateTime> ArrearWEF { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LOG_TIME { get; set; }
        public string LOG_CREATED_BY { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string Requested_by { get; set; }
        public string Request_Reference { get; set; }
        public string Request_Reference_Number { get; set; }
        public Nullable<System.DateTime> REQUEST_RECEIVED_DATE { get; set; }
        public string CREATED_BY1 { get; set; }
        public Nullable<System.DateTime> COMPLETED__DATE { get; set; }
        public string COMPLETED_BY { get; set; }
        public Nullable<System.DateTime> COMMITMENT_BOOKING_DATE { get; set; }
        public Nullable<System.DateTime> COMMMITEE_APPROVED_DATE { get; set; }
        public string MS_PHD_COURSE { get; set; }
    }
}
