//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTEmployeeHistory
    {
        public long RowNumber { get; set; }
        public int HistoryID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public Nullable<System.DateTime> ActualAppointmentEndDate { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public string AppointmentType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> isHRAUpdate { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public Nullable<decimal> GST { get; set; }
        public string Designation { get; set; }
        public string ProjectNumber { get; set; }
        public string OfferLetter { get; set; }
        public string OfficeOrder { get; set; }
        public string JoiningReport { get; set; }
        public Nullable<bool> isUpdated { get; set; }
        public Nullable<bool> isExtended { get; set; }
        public string Status { get; set; }
        public string TypeofAppointment { get; set; }
        public Nullable<int> STEOldOrderHistory { get; set; }
        public Nullable<int> RCTOSGOldOrderId { get; set; }
        public string CommitmentNumber { get; set; }
    }
}
