//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ReceiptDetails
    {
        public string ReceiptNumber { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string Source { get; set; }
        public string InvoiceNumber { get; set; }
        public string ProjectNumber { get; set; }
        public string TransactionNumber { get; set; }
        public string TransactionDate { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public decimal ReceiptOverheadValue { get; set; }
        public int ReceiptId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Status { get; set; }
        public string description { get; set; }
    }
}
