//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTVerificationList
    {
        public long RowNumber { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string Category { get; set; }
        public string ApplicationType { get; set; }
        public string ApplicationNo { get; set; }
        public string Status { get; set; }
        public string CandidateName { get; set; }
        public string PostRecommended { get; set; }
        public Nullable<System.DateTime> UptdTs { get; set; }
        public string PANNo { get; set; }
        public string AadhaarNo { get; set; }
        public string EmployeeNo { get; set; }
        public Nullable<System.DateTime> AppointmentStartdate { get; set; }
        public Nullable<System.DateTime> AppointmentEnddate { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> CancelInitiator { get; set; }
        public Nullable<int> OrderId { get; set; }
    }
}
