//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTOverAllReports
    {
        public long RowNumber { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string ApplicationNumber { get; set; }
        public string Category { get; set; }
        public string CandidateName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Sex { get; set; }
        public string Caste { get; set; }
        public string PANNo { get; set; }
        public string AadhaarNumber { get; set; }
        public string Status { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> AppointmentStartdate { get; set; }
        public Nullable<System.DateTime> AppointmentEnddate { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public string MedicalType { get; set; }
        public Nullable<decimal> MedicalAmount { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<System.DateTime> ApplicationEntryDate { get; set; }
        public string Designation { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectTitle { get; set; }
        public string ProfessionalType { get; set; }
        public string TypeofAppointment { get; set; }
        public string PIName { get; set; }
        public string PIEmail { get; set; }
        public string ContactNumber { get; set; }
        public string Qualification { get; set; }
        public string CommitmentNo { get; set; }
        public string ApplicationType { get; set; }
        public string OrderNo { get; set; }
        public string IITMPensionerorCSIRStaff { get; set; }
        public string CSIRStaffPayMode { get; set; }
        public string MsPhdType { get; set; }
        public string PhdDetail { get; set; }
        public string RollNo { get; set; }
        public string PayType { get; set; }
        public string ToMail { get; set; }
        public string bcc { get; set; }
        public string StaffCategory { get; set; }
        public string PhysicallyChallenged { get; set; }
        public string DepartmentName { get; set; }
        public string EmployeeWorkplace { get; set; }
        public string BankName { get; set; }
        public string BankAccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<bool> IsActiveNow { get; set; }
        public Nullable<System.DateTime> RelieveDate { get; set; }
        public string RequestreceivedfromPI { get; set; }
        public string Othergovtagencyrollno { get; set; }
        public string Created_By { get; set; }
        public string OtherExperience { get; set; }
        public Nullable<decimal> CommitmentAmount { get; set; }
        public Nullable<System.DateTime> RequestReceivedDate { get; set; }
        public Nullable<System.DateTime> ActualAppointmentDate { get; set; }
        public string ModeofRelieving { get; set; }
    }
}
