//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTAdhocEmployeeMaster
    {
        public int HistoryID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public Nullable<System.DateTime> ActualAppointmentEndDate { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public string AppointmentType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<bool> isHRABooking { get; set; }
        public Nullable<System.DateTime> HRABookingDate { get; set; }
        public Nullable<bool> isHRACancellation { get; set; }
        public Nullable<System.DateTime> HRACancellationDate { get; set; }
        public Nullable<bool> InclusiveMedical { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> ExtensionDate { get; set; }
        public Nullable<System.DateTime> RelieveDate { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string ApplicationNumber { get; set; }
        public Nullable<int> TypeofAppointment { get; set; }
        public string EmployeeCategory { get; set; }
        public Nullable<int> ProfessionalType { get; set; }
        public string NAME { get; set; }
        public string NameoftheGuardian { get; set; }
        public string AadhaarNumber { get; set; }
        public string PANNo { get; set; }
        public Nullable<int> Caste { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<int> Bloodgroup { get; set; }
        public Nullable<int> BloodgroupRH { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string PhysicallyChallenged { get; set; }
        public Nullable<bool> MsPhd { get; set; }
        public string PhdDetail { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankName { get; set; }
        public string IFSCCode { get; set; }
        public string StaffCategory { get; set; }
        public string EmergencyContact { get; set; }
        public string departmentcode { get; set; }
        public string DEPARTMENT { get; set; }
        public string PROJECTNO { get; set; }
        public string DesignationCode { get; set; }
        public Nullable<bool> TaxExempted { get; set; }
        public Nullable<bool> PTExempted { get; set; }
        public string Designation { get; set; }
        public string commitmentNo { get; set; }
        public Nullable<bool> IITMPensioner_f { get; set; }
    }
}
