//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTOverAllApplicationEntry
    {
        public Nullable<int> ApplicationId { get; set; }
        public string ApplicationNo { get; set; }
        public string Category { get; set; }
        public string CandidateName { get; set; }
        public string PIName { get; set; }
        public string PIEmail { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ApplicationEntryDate { get; set; }
        public Nullable<System.DateTime> ApplicationReceiveDate { get; set; }
        public Nullable<int> CommitteeMember { get; set; }
        public Nullable<int> CommitteeMembers { get; set; }
        public Nullable<int> Chairperson { get; set; }
        public Nullable<bool> isEmployee { get; set; }
        public string EmployeersID { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string PANNo { get; set; }
        public Nullable<System.DateTime> DateofBrith { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<System.DateTime> UptdTs { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public string Email { get; set; }
        public Nullable<int> PIId { get; set; }
        public Nullable<int> CommitteeApprovedBy { get; set; }
        public Nullable<decimal> CommitmentAmount { get; set; }
        public Nullable<System.DateTime> AppointmentStartdate { get; set; }
        public Nullable<System.DateTime> AppointmentEnddate { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<int> MedicalType { get; set; }
        public Nullable<decimal> MedicalAmmount { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public string PostRecommended { get; set; }
        public string ProfessionalType { get; set; }
        public string TypeofAppointment { get; set; }
        public string Qualification { get; set; }
        public string Experience { get; set; }
        public string AdditionalRequirement { get; set; }
        public string CommitmentNumber { get; set; }
        public Nullable<int> AppointmentType { get; set; }
        public string EmployeeNo { get; set; }
        public string ApplicationType { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Comments { get; set; }
        public string IITMPensionerorCSIRStaff { get; set; }
        public Nullable<int> CSIRStaffPayMode { get; set; }
        public Nullable<bool> isMsPhd { get; set; }
        public string PhdDetail { get; set; }
        public Nullable<bool> ConsolidatedPay { get; set; }
        public Nullable<bool> Fellowship { get; set; }
        public Nullable<int> TypeofAppointmentinInt { get; set; }
        public string CommitteeRemarks { get; set; }
        public string ToMail { get; set; }
        public string bcc { get; set; }
        public Nullable<bool> isCommitmentReject { get; set; }
        public Nullable<bool> isGovAgencyFund { get; set; }
        public string AadhaarNo { get; set; }
        public Nullable<decimal> ExperienceDes { get; set; }
        public Nullable<int> crtdUserId { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public string StaffCategory { get; set; }
        public string PhysicallyChallenged { get; set; }
        public Nullable<bool> IsActiveNow { get; set; }
        public string IITMExperience { get; set; }
        public Nullable<decimal> IITMExperiencedes { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<System.DateTime> RelieveDate { get; set; }
        public string SalaryLevel { get; set; }
    }
}
