//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ReceiptExclInterest
    {
        public string ProjectNumber { get; set; }
        public Nullable<decimal> SanctionValue { get; set; }
        public decimal Oldreceipt { get; set; }
        public decimal Tulareceipt { get; set; }
        public Nullable<decimal> TotalReceipt { get; set; }
    }
}
