//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTProjectTypeCount
    {
        public Nullable<long> RowNumber { get; set; }
        public string AppointmentType { get; set; }
        public int Sponsored { get; set; }
        public int RB { get; set; }
        public int IC { get; set; }
        public int RC { get; set; }
        public int PCF { get; set; }
        public int RMF { get; set; }
        public int Other { get; set; }
        public int Total { get; set; }
    }
}
