//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTOTHPayDeductionReport
    {
        public Nullable<int> AppointmentId { get; set; }
        public Nullable<int> AppointmentType { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeNo { get; set; }
        public string ProjectNumber { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public string MonthandYear { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string SalaryType { get; set; }
        public string ProcessedMonthandYear { get; set; }
        public string ProcessType { get; set; }
        public string IsNoCommitment_f { get; set; }
        public string OtherType { get; set; }
        public string Head { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created_TS { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> Updated_TS { get; set; }
    }
}
