//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTPHDQulifiedEmployees
    {
        public int STEID { get; set; }
        public string EmployeersID { get; set; }
        public string Name { get; set; }
        public string TypeofAppointment { get; set; }
        public string Designation { get; set; }
        public string PIName { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentCode { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public string Course { get; set; }
    }
}
