//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTSTEEmployeeMaster
    {
        public int ApplicationId { get; set; }
        public string ApplicationNo { get; set; }
        public string Category { get; set; }
        public string EmployeeName { get; set; }
        public string PIName { get; set; }
        public string PIEmailID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ApplicationEntryDate { get; set; }
        public Nullable<System.DateTime> ApplicationReceiveDate { get; set; }
        public Nullable<int> CommitteeMember { get; set; }
        public Nullable<int> CommitteeMembers { get; set; }
        public Nullable<int> Chairperson { get; set; }
        public Nullable<bool> isEmployee { get; set; }
        public string EmployeersID { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string PAN { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<System.DateTime> UptdTs { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> PIId { get; set; }
        public Nullable<int> CommitteeApprovedBy { get; set; }
        public Nullable<decimal> CommitmentAmount { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Fathername { get; set; }
        public Nullable<int> VendorName { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<int> MedicalType { get; set; }
        public Nullable<decimal> MedicalAmmount { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public string DesignationName { get; set; }
        public Nullable<int> Age { get; set; }
        public string ProjectNo { get; set; }
        public string EmployeeDepart { get; set; }
        public string ProfDepart { get; set; }
        public string BankAccountNo { get; set; }
        public string BankName { get; set; }
        public string IFSC_Code { get; set; }
        public string MobileNo { get; set; }
        public string EmergencycontactNo { get; set; }
        public string Communicationaddress { get; set; }
        public string Permananentaddress { get; set; }
        public string ProfessionalType { get; set; }
        public string Gender { get; set; }
        public string Caste { get; set; }
        public string BloodGroup { get; set; }
        public string FullorPart { get; set; }
        public string PreviousemploymentOtherthanIITM { get; set; }
        public string HighestQualification { get; set; }
        public string Experience { get; set; }
        public string AdditionalRequirement { get; set; }
        public string CommitmentNumber { get; set; }
        public int AppointmentType { get; set; }
        public string EmployeeNo { get; set; }
        public string ApplicationType { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Comments { get; set; }
        public string IITMPensionerorCSIRStaff { get; set; }
        public Nullable<int> CSIRStaffPayMode { get; set; }
        public Nullable<bool> isMsPhd { get; set; }
        public string PhdDetail { get; set; }
        public Nullable<bool> ConsolidatedPay { get; set; }
        public Nullable<bool> Fellowship { get; set; }
        public Nullable<int> TypeofAppointmentinInt { get; set; }
        public string CommitteeRemarks { get; set; }
        public string ToMail { get; set; }
        public string bcc { get; set; }
        public Nullable<bool> isCommitmentReject { get; set; }
        public Nullable<bool> isGovAgencyFund { get; set; }
        public string AadhaarNo { get; set; }
        public Nullable<decimal> ExperienceDes { get; set; }
        public Nullable<int> crtdUserId { get; set; }
        public int UserRoleId { get; set; }
        public string ICSRNonICSR { get; set; }
        public string PhysicallyChallenged { get; set; }
        public bool IsActiveNow { get; set; }
    }
}
