//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTAnnouncementDataReport
    {
        public string AdvertisementNumber { get; set; }
        public string AnnouncementTitle { get; set; }
        public string Type { get; set; }
        public string PIName { get; set; }
        public string Department { get; set; }
        public string ProjectNumber { get; set; }
        public string RequestReceived { get; set; }
        public string AnnouncementCloseDate_ { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Crt_TS { get; set; }
    }
}
