//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTSalaryAgencyComponentLog
    {
        public int LogId { get; set; }
        public string AgencyName { get; set; }
        public string Component { get; set; }
        public Nullable<decimal> OldComponentValue { get; set; }
        public Nullable<decimal> ComponentValue { get; set; }
        public Nullable<System.DateTime> Created_TS { get; set; }
        public string Created_By { get; set; }
    }
}
