//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTOSGRelievingReport
    {
        public string EMPLOYEE_ID { get; set; }
        public string NAME { get; set; }
        public string FT_PT { get; set; }
        public string ICSR___NON_ICSR { get; set; }
        public string DESIGNATION { get; set; }
        public string PROJECT_NO { get; set; }
        public Nullable<System.DateTime> RELIEVED_ON { get; set; }
        public string No_due___Remarks { get; set; }
        public Nullable<System.DateTime> Crt_TS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LOGCREATED_TIME { get; set; }
        public string LOG_CREATED_BY { get; set; }
    }
}
