//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTSTEExtensionEnhancementReport
    {
        public string EMPLOYEE_ID { get; set; }
        public string NAME { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<System.DateTime> APPOINTMENT_START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public string PROJECT_NO_ { get; set; }
        public string DEPARTMENT { get; set; }
        public string APPOINTMENT_TYPE { get; set; }
        public Nullable<System.DateTime> ARREARS_TO_BE_PROCESSED_W_E_F { get; set; }
        public Nullable<System.DateTime> LOG_TIME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string ENHANCEMENT_TYPE { get; set; }
        public string Requested_by { get; set; }
        public string Request_Reference { get; set; }
        public string Request_Reference_Number { get; set; }
        public Nullable<System.DateTime> REQUEST_RECEIVED_DATE { get; set; }
        public string CREATED_BY1 { get; set; }
        public Nullable<System.DateTime> COMPLETED__DATE { get; set; }
        public string COMPLETED_BY { get; set; }
        public Nullable<System.DateTime> COMMITMENT_BOOKING_DATE { get; set; }
        public Nullable<System.DateTime> COMMMITEE_APPROVED_DATE { get; set; }
        public string MS_PHD_COURSE { get; set; }
    }
}
