//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RCTOSGNewJoineeReport
    {
        public string EMPLOYEE_ID { get; set; }
        public string NAME { get; set; }
        public string EMPL_TYPE { get; set; }
        public string DESIGNATION { get; set; }
        public string PROJECT_NO_ { get; set; }
        public string Department_Name { get; set; }
        public string COMMITMENT_NO { get; set; }
        public Nullable<System.DateTime> FROM { get; set; }
        public Nullable<System.DateTime> TO { get; set; }
        public Nullable<decimal> PF_BASIC { get; set; }
        public Nullable<decimal> GROSS_PAY { get; set; }
        public string PF_Eligiblity { get; set; }
        public string ESIC_Eligiblity { get; set; }
        public Nullable<int> ARREARS_TO_BE_PROCESSED_W_E_F { get; set; }
        public Nullable<System.DateTime> Request_received_date { get; set; }
        public string INITIATED_BY { get; set; }
        public Nullable<System.DateTime> INITIATED_DATE { get; set; }
        public string APPROVED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string COMMITMENTBOOKED_BY { get; set; }
        public Nullable<System.DateTime> COMMITMENT_BOOKING_DATE { get; set; }
        public Nullable<System.DateTime> COMMMITEE_APPROVED_DATE { get; set; }
        public string VERIFICATION_INITIATED_BY { get; set; }
        public Nullable<System.DateTime> VERIFICATION_INITIATED_DATE { get; set; }
        public string VERIFICATION_APPROVED_BY { get; set; }
        public Nullable<System.DateTime> VERIFICATION_APPROVED_DATE { get; set; }
        public string BANK_NAME { get; set; }
        public string ACCOUNT_NO_ { get; set; }
        public string IFSC_CODE { get; set; }
        public string NIDNumber { get; set; }
        public string Initiated_by1 { get; set; }
    }
}
