//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SponsoredProjects
    {
        public int projectid { get; set; }
        public string projectNumber { get; set; }
        public string ProjectTitle { get; set; }
        public string departmentName { get; set; }
        public string FirstName { get; set; }
        public Nullable<decimal> BaseValue { get; set; }
        public Nullable<System.DateTime> crtdTs { get; set; }
        public Nullable<decimal> ApplicableTax { get; set; }
        public string ProjectCoPi { get; set; }
        public string MonthYear { get; set; }
        public string AgencyName { get; set; }
        public string AgencyCode { get; set; }
        public Nullable<int> ProjectClassification { get; set; }
    }
}
