//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SchemeDetails
    {
        public string ProjectSchemeCode { get; set; }
        public string ChangedSchemeCode { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> Closed { get; set; }
        public string Transfered { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
