//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SRBReport
    {
        public int tblSRBDetailId { get; set; }
        public int SRBId { get; set; }
        public string SRBNumber { get; set; }
        public string NameoftheEquipment { get; set; }
        public string Category { get; set; }
        public string SupplierName { get; set; }
        public string PONumber { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<decimal> ItemValue { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<System.DateTime> InwardDate { get; set; }
        public string Is_Asset { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string UOM { get; set; }
        public string BuyBack { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
