//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SourceofFunding
    {
        public int ProjectId { get; set; }
        public Nullable<decimal> BaseValue { get; set; }
        public Nullable<decimal> ApplicableTax { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public string Companytype { get; set; }
        public string Monthyear { get; set; }
    }
}
