//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Subleadgers
    {
        public int pKey { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> SubLeadgerType { get; set; }
        public string Category { get; set; }
        public string EmployeeId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string DepartmentCode { get; set; }
        public string Designation { get; set; }
        public string DepartmentName { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> BankType { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string Branch { get; set; }
        public string BankName { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string ContactPerson { get; set; }
        public string PAN { get; set; }
        public string GSTIN { get; set; }
        public string TAN { get; set; }
        public Nullable<int> SeqNbr { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> StateCode { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<bool> GSTExempted { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> TDSExcempted { get; set; }
    }
}
