//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SRB
    {
        public string SRBNumber { get; set; }
        public Nullable<System.DateTime> InwardDate { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string Remarks { get; set; }
        public string SupplierName { get; set; }
        public Nullable<decimal> NetTotalAmount { get; set; }
        public Nullable<decimal> Taxrate { get; set; }
        public string Status { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ItemValue { get; set; }
        public string Asset { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
