//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TravelAdvandSett
    {
        public string PIName { get; set; }
        public string BillNumber { get; set; }
        public Nullable<decimal> AdvanceValue { get; set; }
        public Nullable<System.DateTime> AdvanceDate { get; set; }
        public string AdvanceStatus { get; set; }
        public string SettBillNumber { get; set; }
        public string PayeeName { get; set; }
        public string Place { get; set; }
        public Nullable<System.DateTime> TripFromDate { get; set; }
        public Nullable<System.DateTime> TripToDate { get; set; }
        public string TravellerName { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectType { get; set; }
        public Nullable<decimal> SettAmount { get; set; }
        public Nullable<decimal> OverAllExpense { get; set; }
        public Nullable<System.DateTime> SettDate { get; set; }
        public string SettStatus { get; set; }
        public Nullable<int> Ageing { get; set; }
        public string OutstandingStatus { get; set; }
    }
}
