//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TempApprovalFlow
    {
        public int FunctionId { get; set; }
        public Nullable<int> ProcessTransactionId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ApproverLevel { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<int> ProcessSeqNumber { get; set; }
        public Nullable<int> CurrentApproverId { get; set; }
        public string ActionStatus { get; set; }
        public Nullable<System.DateTime> TransactionTS { get; set; }
        public string ActionLink { get; set; }
        public string FunctionName { get; set; }
        public string ID { get; set; }
        public string RefNumber { get; set; }
        public Nullable<int> ProcessGuidelineId { get; set; }
        public string ProcessGuidelineTitle { get; set; }
        public Nullable<int> ProcessGuidelineDetailId { get; set; }
        public string FlowTitle { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RefId { get; set; }
        public Nullable<bool> Approve_f { get; set; }
        public Nullable<bool> Reject_f { get; set; }
        public Nullable<bool> Clarify_f { get; set; }
        public Nullable<bool> Mark_f { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string TransactionIP { get; set; }
        public string MacID { get; set; }
        public Nullable<int> ProcessTransactionDetailId { get; set; }
        public string RefTable { get; set; }
        public Nullable<bool> Clarified { get; set; }
        public Nullable<bool> Rejected { get; set; }
    }
}
