//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TravelbillNo
    {
        public string BillNumber { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public string Status { get; set; }
        public Nullable<int> Place { get; set; }
        public Nullable<int> TravelFromDate { get; set; }
        public Nullable<int> TravelToDate { get; set; }
        public int TravelBillId { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> TravelBillDetailId { get; set; }
        public Nullable<decimal> Advancevalue { get; set; }
        public Nullable<int> reftravelbillid { get; set; }
        public string RefBillNumber { get; set; }
    }
}
