//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TravelCommitment
    {
        public string TransactionTypeCode { get; set; }
        public string BillNumber { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public int TravelBillCommitmentDetailId { get; set; }
        public Nullable<int> TravelBillId { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string Status { get; set; }
        public string CommitmentNumber { get; set; }
        public Nullable<decimal> CommitmentAmount { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectType { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> CommitmentBalanceAmount { get; set; }
        public string HeadName { get; set; }
        public Nullable<System.DateTime> ProjectCloseDate { get; set; }
        public string CommitmentStatus { get; set; }
    }
}
