//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Tapal
    {
        public int TapalId { get; set; }
        public string TapalNo { get; set; }
        public string SenderName { get; set; }
        public Nullable<System.DateTime> SenderDate { get; set; }
        public string Notes { get; set; }
        public string Receiver1 { get; set; }
        public Nullable<System.DateTime> Receiver1Date { get; set; }
        public string Receiver2 { get; set; }
        public Nullable<System.DateTime> Receiver2Date { get; set; }
        public Nullable<int> PIId { get; set; }
        public string PINAME { get; set; }
        public Nullable<System.DateTime> TapalDate { get; set; }
        public int Receiver1Id { get; set; }
        public int Receiver2Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string ProjectNumber { get; set; }
    }
}
