//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UTRwithTapal
    {
        public int UTRwithTapalId { get; set; }
        public string BatchNumber { get; set; }
        public string Payee { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string BankAccount { get; set; }
        public string IFSC { get; set; }
        public string AccountNumber { get; set; }
        public string Branch { get; set; }
        public string Remarks { get; set; }
        public string PayeeBank { get; set; }
        public string IOASRef { get; set; }
        public string BatchStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string UTRNumber { get; set; }
        public Nullable<System.DateTime> InputValueDate { get; set; }
        public string UTRStatus { get; set; }
        public string BatchMasterStatus { get; set; }
        public string TapalNo { get; set; }
    }
}
