//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserWiseBill
    {
        public string RefNo { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DepartmentName { get; set; }
        public string FunctionName { get; set; }
        public int RefId { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> TapalNo { get; set; }
        public Nullable<int> SourceEmailDate { get; set; }
    }
}
