//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_vendorsCategoryId
    {
        public int VendorMaster { get; set; }
        public string pan { get; set; }
        public int VendorId { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public string RegisteredName { get; set; }
        public string Email { get; set; }
        public string AccountNumber { get; set; }
    }
}
