//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProjectDetails
    {
        public string Type { get; set; }
        public Nullable<decimal> SanctionValue { get; set; }
        public string Year { get; set; }
        public string Classification { get; set; }
        public string AgencyName { get; set; }
        public string ProjectNumber { get; set; }
        public string SanctionOrderNumber { get; set; }
        public string PI { get; set; }
        public string Email { get; set; }
        public string DepartmentCode { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public string SchemeName { get; set; }
        public int ProjectId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> SanctionOrderDate { get; set; }
        public string DomainName { get; set; }
        public string DomainDescription { get; set; }
        public string SchemeCode { get; set; }
    }
}
