//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTandM
    {
        public string EmployeeName { get; set; }
        public string MeetingID { get; set; }
        public string CandidateID { get; set; }
        public System.DateTime DOB { get; set; }
        public string DesignationCode { get; set; }
        public string DesignationName { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public Nullable<System.DateTime> RelieveDate { get; set; }
        public string PermanentAddress { get; set; }
        public string CommunicationAddress { get; set; }
        public string MobileNumber { get; set; }
        public string EmailID { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string BankAccountNo { get; set; }
        public string IFSC_Code { get; set; }
        public string OutSourcingCompany { get; set; }
        public Nullable<bool> NoDue { get; set; }
        public string OrderType { get; set; }
        public string ProjectNo { get; set; }
        public System.DateTime FromDate { get; set; }
        public decimal CostToProject { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal HRA { get; set; }
        public decimal Bonus { get; set; }
        public decimal SpecialAllowance { get; set; }
        public decimal GrossSalary { get; set; }
        public decimal EmployeePF { get; set; }
        public decimal EmployeeESIC { get; set; }
        public decimal ProfessionalTax { get; set; }
        public decimal NetSalary { get; set; }
        public decimal EmployerPF { get; set; }
        public decimal EmployerESIC { get; set; }
        public decimal Insurance { get; set; }
        public decimal TotalContribution { get; set; }
        public decimal GrossTotal { get; set; }
        public decimal AgencyFee { get; set; }
        public decimal ServiceTax { get; set; }
        public decimal TotalSalary { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Remarks { get; set; }
        public int OrderID { get; set; }
        public string CommitmentNo { get; set; }
        public string EmployeeId { get; set; }
    }
}
