//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTapalDetails
    {
        public string SenderDetail { get; set; }
        public Nullable<bool> IsInward { get; set; }
        public string TapalType { get; set; }
        public string PI { get; set; }
        public string ProjectNo { get; set; }
        public Nullable<bool> ProjectTabal { get; set; }
        public Nullable<int> MarkTo { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> OutwardDateTime { get; set; }
        public Nullable<System.DateTime> InwardDateTime { get; set; }
        public string Active { get; set; }
        public Nullable<System.DateTime> CreatedTS { get; set; }
        public string CreatedBy { get; set; }
        public string UserName { get; set; }
    }
}
